# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module WorkOS
  module Encryptors
    class AesGcm
      SEAL_VERSION = T.let(0x01, Integer)

      sig { params(data: T.any(String, T::Hash[T.untyped, T.untyped]), key: String).returns(String) }
      def seal(data, key); end

      sig { params(sealed: String, key: String).returns(T.any(T::Hash[String, T.untyped], String)) }
      def unseal(sealed, key); end
    end
  end
end
