# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class GroupsModelRoundTripTest < Minitest::Test
  def test_user_organization_membership_base_list_data_round_trip
    fixture = {
      "object" => "organization_membership",
      "id" => "stub",
      "user_id" => "stub",
      "organization_id" => "stub",
      "status" => "stub",
      "directory_managed" => true,
      "organization_name" => "stub",
      "custom_attributes" => {},
      "created_at" => "stub",
      "updated_at" => "stub",
      "user" => {}
    }
    model = WorkOS::UserOrganizationMembershipBaseListData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["user_id"], json[:user_id]
    assert_equal fixture["organization_id"], json[:organization_id]
    assert_equal fixture["directory_managed"], json[:directory_managed]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end
end
