# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class ClientApiModelRoundTripTest < Minitest::Test
  def test_client_api_token_round_trip
    fixture = {
      "organization_id" => "stub",
      "user_id" => "stub"
    }
    model = WorkOS::ClientApiToken.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["organization_id"], json[:organization_id]
    assert_equal fixture["user_id"], json[:user_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_client_api_token_response_round_trip
    fixture = {
      "token" => "stub"
    }
    model = WorkOS::ClientApiTokenResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["token"], json[:token]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end
end
