# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class UserManagementOrganizationMembershipGroupsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = WorkOS::Client.new(api_key: "sk_test_123")
  end

  def test_list_organization_membership_groups_returns_expected_result
    stub_request(:get, %r{\Ahttps://api\.workos\.com/user_management/organization_memberships/stub/groups(\?|\z)})
      .to_return(body: '{"data": [], "list_metadata": {}}', status: 200)
    result = @client.user_management_organization_membership_groups.list_organization_membership_groups(om_id: "stub")
    assert_kind_of WorkOS::Types::ListStruct, result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    { name: :list_organization_membership_groups, verb: :get, url: %r{\Ahttps://api\.workos\.com/user_management/organization_memberships/stub/groups(\?|\z)}, args: { om_id: "stub" } },
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(WorkOS::AuthenticationError) do
        @client.user_management_organization_membership_groups.send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
