# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class UserManagementTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = WorkOS::Client.new(api_key: "sk_test_123")
  end

  def test_get_jwks_returns_expected_result
    stub_request(:get, /#{Regexp.escape("sso")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_jwks(client_id: "stub")
    refute_nil result
  end

  def test_get_jwks_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("sso")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_jwks(client_id: "stub")
    end
  end

  def test_create_authenticate_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.create_authenticate(client_id: "stub", client_secret: "stub", grant_type: "authorization_code", code: "stub")
    refute_nil result
  end

  def test_create_authenticate_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.create_authenticate(client_id: "stub", client_secret: "stub", grant_type: "authorization_code", code: "stub")
    end
  end

  def test_authenticate_with_password_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_password(email: "stub", password: "stub")
    refute_nil result
  end

  def test_authenticate_with_password_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_password(email: "stub", password: "stub")
    end
  end

  def test_authenticate_with_code_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_code(code: "stub")
    refute_nil result
  end

  def test_authenticate_with_code_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_code(code: "stub")
    end
  end

  def test_authenticate_with_refresh_token_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_refresh_token(refresh_token: "stub")
    refute_nil result
  end

  def test_authenticate_with_refresh_token_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_refresh_token(refresh_token: "stub")
    end
  end

  def test_authenticate_with_magic_auth_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_magic_auth(code: "stub", email: "stub")
    refute_nil result
  end

  def test_authenticate_with_magic_auth_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_magic_auth(code: "stub", email: "stub")
    end
  end

  def test_authenticate_with_email_verification_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_email_verification(code: "stub", pending_authentication_token: "stub")
    refute_nil result
  end

  def test_authenticate_with_email_verification_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_email_verification(code: "stub", pending_authentication_token: "stub")
    end
  end

  def test_authenticate_with_totp_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_totp(code: "stub", pending_authentication_token: "stub", authentication_challenge_id: "stub")
    refute_nil result
  end

  def test_authenticate_with_totp_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_totp(code: "stub", pending_authentication_token: "stub", authentication_challenge_id: "stub")
    end
  end

  def test_authenticate_with_organization_selection_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_organization_selection(pending_authentication_token: "stub", organization_id: "stub")
    refute_nil result
  end

  def test_authenticate_with_organization_selection_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_organization_selection(pending_authentication_token: "stub", organization_id: "stub")
    end
  end

  def test_authenticate_with_device_code_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.authenticate_with_device_code(device_code: "stub")
    refute_nil result
  end

  def test_authenticate_with_device_code_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.authenticate_with_device_code(device_code: "stub")
    end
  end

  def test_create_device_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.create_device(client_id: "stub")
    refute_nil result
  end

  def test_create_device_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.create_device(client_id: "stub")
    end
  end

  def test_revoke_session_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.revoke_session(session_id: "stub")
    assert_nil result if result.nil?
  end

  def test_revoke_session_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.revoke_session(session_id: "stub")
    end
  end

  def test_create_cors_origin_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.create_cors_origin(origin: "stub")
    refute_nil result
  end

  def test_create_cors_origin_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.create_cors_origin(origin: "stub")
    end
  end

  def test_get_email_verification_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_email_verification(id: "stub")
    refute_nil result
  end

  def test_get_email_verification_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_email_verification(id: "stub")
    end
  end

  def test_reset_password_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.reset_password(email: "stub")
    refute_nil result
  end

  def test_reset_password_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.reset_password(email: "stub")
    end
  end

  def test_confirm_password_reset_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.confirm_password_reset(token: "stub", new_password: "stub")
    refute_nil result
  end

  def test_confirm_password_reset_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.confirm_password_reset(token: "stub", new_password: "stub")
    end
  end

  def test_get_password_reset_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_password_reset(id: "stub")
    refute_nil result
  end

  def test_get_password_reset_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_password_reset(id: "stub")
    end
  end

  def test_list_users_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"data": [], "list_metadata": {}}', status: 200)
    result = @client.user_management.list_users
    assert_kind_of WorkOS::Types::ListStruct, result
  end

  def test_list_users_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.list_users
    end
  end

  def test_create_user_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.create_user(email: "stub")
    refute_nil result
  end

  def test_create_user_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.create_user(email: "stub")
    end
  end

  def test_get_user_by_external_id_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_user_by_external_id(external_id: "stub")
    refute_nil result
  end

  def test_get_user_by_external_id_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_user_by_external_id(external_id: "stub")
    end
  end

  def test_get_user_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_user(id: "stub")
    refute_nil result
  end

  def test_get_user_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_user(id: "stub")
    end
  end

  def test_update_user_returns_expected_result
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.update_user(id: "stub")
    refute_nil result
  end

  def test_update_user_raises_authentication_error_on_401
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.update_user(id: "stub")
    end
  end

  def test_delete_user_returns_expected_result
    stub_request(:delete, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.delete_user(id: "stub")
    assert_nil result if result.nil?
  end

  def test_delete_user_raises_authentication_error_on_401
    stub_request(:delete, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.delete_user(id: "stub")
    end
  end

  def test_confirm_email_change_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.confirm_email_change(id: "stub", code: "stub")
    refute_nil result
  end

  def test_confirm_email_change_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.confirm_email_change(id: "stub", code: "stub")
    end
  end

  def test_send_email_change_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.send_email_change(id: "stub", new_email: "stub")
    refute_nil result
  end

  def test_send_email_change_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.send_email_change(id: "stub", new_email: "stub")
    end
  end

  def test_verify_email_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.verify_email(id: "stub", code: "stub")
    refute_nil result
  end

  def test_verify_email_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.verify_email(id: "stub", code: "stub")
    end
  end

  def test_send_verification_email_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.send_verification_email(id: "stub")
    refute_nil result
  end

  def test_send_verification_email_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.send_verification_email(id: "stub")
    end
  end

  def test_get_user_identities_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_user_identities(id: "stub")
    refute_nil result
  end

  def test_get_user_identities_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_user_identities(id: "stub")
    end
  end

  def test_list_sessions_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"data": [], "list_metadata": {}}', status: 200)
    result = @client.user_management.list_sessions(id: "stub")
    assert_kind_of WorkOS::Types::ListStruct, result
  end

  def test_list_sessions_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.list_sessions(id: "stub")
    end
  end

  def test_list_invitations_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"data": [], "list_metadata": {}}', status: 200)
    result = @client.user_management.list_invitations
    assert_kind_of WorkOS::Types::ListStruct, result
  end

  def test_list_invitations_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.list_invitations
    end
  end

  def test_send_invitation_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.send_invitation(email: "stub")
    refute_nil result
  end

  def test_send_invitation_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.send_invitation(email: "stub")
    end
  end

  def test_find_invitation_by_token_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.find_invitation_by_token(token: "stub")
    refute_nil result
  end

  def test_find_invitation_by_token_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.find_invitation_by_token(token: "stub")
    end
  end

  def test_get_invitation_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_invitation(id: "stub")
    refute_nil result
  end

  def test_get_invitation_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_invitation(id: "stub")
    end
  end

  def test_accept_invitation_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.accept_invitation(id: "stub")
    refute_nil result
  end

  def test_accept_invitation_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.accept_invitation(id: "stub")
    end
  end

  def test_resend_invitation_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.resend_invitation(id: "stub")
    refute_nil result
  end

  def test_resend_invitation_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.resend_invitation(id: "stub")
    end
  end

  def test_revoke_invitation_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.revoke_invitation(id: "stub")
    refute_nil result
  end

  def test_revoke_invitation_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.revoke_invitation(id: "stub")
    end
  end

  def test_update_jwt_template_returns_expected_result
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.update_jwt_template(content: "stub")
    refute_nil result
  end

  def test_update_jwt_template_raises_authentication_error_on_401
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.update_jwt_template(content: "stub")
    end
  end

  def test_create_magic_auth_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.create_magic_auth(email: "stub")
    refute_nil result
  end

  def test_create_magic_auth_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.create_magic_auth(email: "stub")
    end
  end

  def test_get_magic_auth_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_magic_auth(id: "stub")
    refute_nil result
  end

  def test_get_magic_auth_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_magic_auth(id: "stub")
    end
  end

  def test_list_organization_memberships_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"data": [], "list_metadata": {}}', status: 200)
    result = @client.user_management.list_organization_memberships
    assert_kind_of WorkOS::Types::ListStruct, result
  end

  def test_list_organization_memberships_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.list_organization_memberships
    end
  end

  def test_create_organization_membership_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.create_organization_membership(user_id: "stub", organization_id: "stub")
    refute_nil result
  end

  def test_create_organization_membership_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.create_organization_membership(user_id: "stub", organization_id: "stub")
    end
  end

  def test_get_organization_membership_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.get_organization_membership(id: "stub")
    refute_nil result
  end

  def test_get_organization_membership_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.get_organization_membership(id: "stub")
    end
  end

  def test_update_organization_membership_returns_expected_result
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.update_organization_membership(id: "stub")
    refute_nil result
  end

  def test_update_organization_membership_raises_authentication_error_on_401
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.update_organization_membership(id: "stub")
    end
  end

  def test_delete_organization_membership_returns_expected_result
    stub_request(:delete, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.delete_organization_membership(id: "stub")
    assert_nil result if result.nil?
  end

  def test_delete_organization_membership_raises_authentication_error_on_401
    stub_request(:delete, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.delete_organization_membership(id: "stub")
    end
  end

  def test_deactivate_organization_membership_returns_expected_result
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.deactivate_organization_membership(id: "stub")
    refute_nil result
  end

  def test_deactivate_organization_membership_raises_authentication_error_on_401
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.deactivate_organization_membership(id: "stub")
    end
  end

  def test_reactivate_organization_membership_returns_expected_result
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.reactivate_organization_membership(id: "stub")
    refute_nil result
  end

  def test_reactivate_organization_membership_raises_authentication_error_on_401
    stub_request(:put, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.reactivate_organization_membership(id: "stub")
    end
  end

  def test_create_redirect_uri_returns_expected_result
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.create_redirect_uri(uri: "stub")
    refute_nil result
  end

  def test_create_redirect_uri_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.create_redirect_uri(uri: "stub")
    end
  end

  def test_list_user_authorized_applications_returns_expected_result
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"data": [], "list_metadata": {}}', status: 200)
    result = @client.user_management.list_user_authorized_applications(user_id: "stub")
    assert_kind_of WorkOS::Types::ListStruct, result
  end

  def test_list_user_authorized_applications_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.list_user_authorized_applications(user_id: "stub")
    end
  end

  def test_delete_user_authorized_application_returns_expected_result
    stub_request(:delete, /#{Regexp.escape("user_management")}/)
      .to_return(body: "{}", status: 200)
    result = @client.user_management.delete_user_authorized_application(application_id: "stub", user_id: "stub")
    assert_nil result if result.nil?
  end

  def test_delete_user_authorized_application_raises_authentication_error_on_401
    stub_request(:delete, /#{Regexp.escape("user_management")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.user_management.delete_user_authorized_application(application_id: "stub", user_id: "stub")
    end
  end
end
