# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class UserManagementModelRoundTripTest < Minitest::Test
  def test_create_cors_origin_round_trip
    fixture = {
      "origin" => "stub"
    }
    model = WorkOS::CreateCORSOrigin.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["origin"], json[:origin]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_update_jwt_template_round_trip
    fixture = {
      "content" => "stub"
    }
    model = WorkOS::UpdateJWTTemplate.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["content"], json[:content]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_redirect_uri_round_trip
    fixture = {
      "uri" => "stub"
    }
    model = WorkOS::CreateRedirectUri.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["uri"], json[:uri]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_magic_code_and_return_round_trip
    fixture = {
      "email" => "stub",
      "invitation_token" => "stub"
    }
    model = WorkOS::CreateMagicCodeAndReturn.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["email"], json[:email]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_user_invite_options_round_trip
    fixture = {
      "email" => "stub",
      "organization_id" => "stub",
      "role_slug" => "stub",
      "expires_in_days" => 1,
      "inviter_user_id" => "stub",
      "locale" => "stub"
    }
    model = WorkOS::CreateUserInviteOptions.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["email"], json[:email]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_resend_user_invite_options_round_trip
    fixture = {
      "locale" => "stub"
    }
    model = WorkOS::ResendUserInviteOptions.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_user_api_key_round_trip
    fixture = {
      "name" => "stub",
      "organization_id" => "stub",
      "permissions" => [],
      "expires_at" => "stub"
    }
    model = WorkOS::CreateUserApiKey.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["organization_id"], json[:organization_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_user_round_trip
    fixture = {
      "email" => "stub",
      "first_name" => nil,
      "last_name" => nil,
      "name" => nil,
      "email_verified" => nil,
      "metadata" => nil,
      "external_id" => nil,
      "password" => nil,
      "password_hash" => "stub",
      "password_hash_type" => "stub"
    }
    model = WorkOS::CreateUser.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["email"], json[:email]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_update_user_round_trip
    fixture = {
      "email" => "stub",
      "first_name" => "stub",
      "last_name" => "stub",
      "name" => "stub",
      "email_verified" => true,
      "metadata" => nil,
      "external_id" => nil,
      "locale" => nil,
      "password" => "stub",
      "password_hash" => "stub",
      "password_hash_type" => "stub"
    }
    model = WorkOS::UpdateUser.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_verify_email_address_round_trip
    fixture = {
      "code" => "stub"
    }
    model = WorkOS::VerifyEmailAddress.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["code"], json[:code]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_password_reset_token_round_trip
    fixture = {
      "email" => "stub"
    }
    model = WorkOS::CreatePasswordResetToken.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["email"], json[:email]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_password_reset_round_trip
    fixture = {
      "token" => "stub",
      "new_password" => "stub"
    }
    model = WorkOS::CreatePasswordReset.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["token"], json[:token]
    assert_equal fixture["new_password"], json[:new_password]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_send_email_change_round_trip
    fixture = {
      "new_email" => "stub"
    }
    model = WorkOS::SendEmailChange.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["new_email"], json[:new_email]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_email_change_round_trip
    fixture = {
      "code" => "stub"
    }
    model = WorkOS::ConfirmEmailChange.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["code"], json[:code]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_revoke_session_round_trip
    fixture = {
      "session_id" => "stub"
    }
    model = WorkOS::RevokeSession.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["session_id"], json[:session_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_round_trip
    fixture = {
      "object" => "user",
      "id" => "stub",
      "first_name" => nil,
      "last_name" => nil,
      "name" => nil,
      "profile_picture_url" => nil,
      "email" => "stub",
      "email_verified" => true,
      "external_id" => nil,
      "metadata" => {},
      "last_sign_in_at" => nil,
      "locale" => nil,
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::User.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_nil json[:first_name]
    assert_nil json[:last_name]
    assert_nil json[:profile_picture_url]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["email_verified"], json[:email_verified]
    assert_nil json[:external_id]
    assert_nil json[:last_sign_in_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cors_origin_response_round_trip
    fixture = {
      "object" => "cors_origin",
      "id" => "stub",
      "origin" => "stub",
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::CORSOriginResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["origin"], json[:origin]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_redirect_uri_round_trip
    fixture = {
      "object" => "redirect_uri",
      "id" => "stub",
      "uri" => "stub",
      "default" => true,
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::RedirectUri.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["uri"], json[:uri]
    assert_equal fixture["default"], json[:default]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_magic_auth_round_trip
    fixture = {
      "object" => "magic_auth",
      "id" => "stub",
      "user_id" => "stub",
      "email" => "stub",
      "expires_at" => "stub",
      "created_at" => "stub",
      "updated_at" => "stub",
      "code" => "stub"
    }
    model = WorkOS::MagicAuth.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["user_id"], json[:user_id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["expires_at"], json[:expires_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    assert_equal fixture["code"], json[:code]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_invite_round_trip
    fixture = {
      "object" => "invitation",
      "id" => "stub",
      "email" => "stub",
      "state" => "stub",
      "accepted_at" => nil,
      "revoked_at" => nil,
      "expires_at" => "stub",
      "organization_id" => nil,
      "inviter_user_id" => nil,
      "accepted_user_id" => nil,
      "role_slug" => nil,
      "created_at" => "stub",
      "updated_at" => "stub",
      "token" => "stub",
      "accept_invitation_url" => "stub"
    }
    model = WorkOS::UserInvite.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_nil json[:accepted_at]
    assert_nil json[:revoked_at]
    assert_equal fixture["expires_at"], json[:expires_at]
    assert_nil json[:organization_id]
    assert_nil json[:inviter_user_id]
    assert_nil json[:accepted_user_id]
    assert_nil json[:role_slug]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    assert_equal fixture["token"], json[:token]
    assert_equal fixture["accept_invitation_url"], json[:accept_invitation_url]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_api_key_round_trip
    fixture = {
      "object" => "api_key",
      "id" => "stub",
      "owner" => {},
      "name" => "stub",
      "obfuscated_value" => "stub",
      "last_used_at" => nil,
      "expires_at" => nil,
      "permissions" => [],
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::UserApiKey.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["obfuscated_value"], json[:obfuscated_value]
    assert_nil json[:last_used_at]
    assert_nil json[:expires_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_api_key_with_value_round_trip
    fixture = {
      "object" => "api_key",
      "id" => "stub",
      "owner" => {},
      "name" => "stub",
      "obfuscated_value" => "stub",
      "last_used_at" => nil,
      "expires_at" => nil,
      "permissions" => [],
      "created_at" => "stub",
      "updated_at" => "stub",
      "value" => "stub"
    }
    model = WorkOS::UserApiKeyWithValue.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["obfuscated_value"], json[:obfuscated_value]
    assert_nil json[:last_used_at]
    assert_nil json[:expires_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    assert_equal fixture["value"], json[:value]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_email_verification_round_trip
    fixture = {
      "object" => "email_verification",
      "id" => "stub",
      "user_id" => "stub",
      "email" => "stub",
      "expires_at" => "stub",
      "created_at" => "stub",
      "updated_at" => "stub",
      "code" => "stub"
    }
    model = WorkOS::EmailVerification.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["user_id"], json[:user_id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["expires_at"], json[:expires_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    assert_equal fixture["code"], json[:code]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_send_verification_email_response_round_trip
    fixture = {
      "user" => {}
    }
    model = WorkOS::SendVerificationEmailResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_verify_email_response_round_trip
    fixture = {
      "user" => {}
    }
    model = WorkOS::VerifyEmailResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_password_reset_round_trip
    fixture = {
      "object" => "password_reset",
      "id" => "stub",
      "user_id" => "stub",
      "email" => "stub",
      "expires_at" => "stub",
      "created_at" => "stub",
      "password_reset_token" => "stub",
      "password_reset_url" => "stub"
    }
    model = WorkOS::PasswordReset.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["user_id"], json[:user_id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["expires_at"], json[:expires_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["password_reset_token"], json[:password_reset_token]
    assert_equal fixture["password_reset_url"], json[:password_reset_url]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_reset_password_response_round_trip
    fixture = {
      "user" => {}
    }
    model = WorkOS::ResetPasswordResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_email_change_round_trip
    fixture = {
      "object" => "email_change",
      "user" => {},
      "new_email" => "stub",
      "expires_at" => "stub",
      "created_at" => "stub"
    }
    model = WorkOS::EmailChange.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["new_email"], json[:new_email]
    assert_equal fixture["expires_at"], json[:expires_at]
    assert_equal fixture["created_at"], json[:created_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_authenticate_response_round_trip
    fixture = {
      "user" => {},
      "organization_id" => "stub",
      "authkit_authorization_code" => "stub",
      "access_token" => "stub",
      "refresh_token" => "stub",
      "authentication_method" => "stub",
      "impersonator" => {},
      "oauth_tokens" => {}
    }
    model = WorkOS::AuthenticateResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["access_token"], json[:access_token]
    assert_equal fixture["refresh_token"], json[:refresh_token]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_device_authorization_response_round_trip
    fixture = {
      "device_code" => "stub",
      "user_code" => "stub",
      "verification_uri" => "stub",
      "verification_uri_complete" => "stub",
      "expires_in" => 1.0,
      "interval" => 1.0
    }
    model = WorkOS::DeviceAuthorizationResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["device_code"], json[:device_code]
    assert_equal fixture["user_code"], json[:user_code]
    assert_equal fixture["verification_uri"], json[:verification_uri]
    assert_equal fixture["expires_in"], json[:expires_in]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_jwks_response_round_trip
    fixture = {
      "keys" => []
    }
    model = WorkOS::JwksResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_jwt_template_response_round_trip
    fixture = {
      "object" => "jwt_template",
      "content" => "stub",
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::JWTTemplateResponse.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["content"], json[:content]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_jwks_response_keys_round_trip
    fixture = {
      "alg" => "RS256",
      "kty" => "RSA",
      "use" => "sig",
      "x5c" => [],
      "n" => "stub",
      "e" => "stub",
      "kid" => "stub",
      "x5t#S256" => "stub"
    }
    model = WorkOS::JwksResponseKeys.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["n"], json[:n]
    assert_equal fixture["e"], json[:e]
    assert_equal fixture["kid"], json[:kid]
    assert_equal fixture["x5t#S256"], json["x5t#S256"]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_authenticate_response_impersonator_round_trip
    fixture = {
      "email" => "stub",
      "reason" => nil
    }
    model = WorkOS::AuthenticateResponseImpersonator.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["email"], json[:email]
    assert_nil json[:reason]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_authenticate_response_oauth_token_round_trip
    fixture = {
      "provider" => "stub",
      "refresh_token" => "stub",
      "access_token" => "stub",
      "expires_at" => 1,
      "scopes" => []
    }
    model = WorkOS::AuthenticateResponseOAuthToken.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["provider"], json[:provider]
    assert_equal fixture["refresh_token"], json[:refresh_token]
    assert_equal fixture["access_token"], json[:access_token]
    assert_equal fixture["expires_at"], json[:expires_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_api_key_with_value_owner_round_trip
    fixture = {
      "type" => "user",
      "id" => "stub",
      "organization_id" => "stub"
    }
    model = WorkOS::UserApiKeyWithValueOwner.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["organization_id"], json[:organization_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_api_key_owner_round_trip
    fixture = {
      "type" => "user",
      "id" => "stub",
      "organization_id" => "stub"
    }
    model = WorkOS::UserApiKeyOwner.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["organization_id"], json[:organization_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_authorization_code_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "client_secret" => "stub",
      "grant_type" => "authorization_code",
      "code" => "stub",
      "code_verifier" => "stub",
      "invitation_token" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::AuthorizationCodeSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["code"], json[:code]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_password_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "client_secret" => "stub",
      "grant_type" => "password",
      "email" => "stub",
      "password" => "stub",
      "invitation_token" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::PasswordSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["client_secret"], json[:client_secret]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["password"], json[:password]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_refresh_token_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "client_secret" => "stub",
      "grant_type" => "refresh_token",
      "refresh_token" => "stub",
      "organization_id" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::RefreshTokenSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["refresh_token"], json[:refresh_token]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_magic_auth_code_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "client_secret" => "stub",
      "grant_type" => "urn:workos:oauth:grant-type:magic-auth:code",
      "code" => "stub",
      "email" => "stub",
      "invitation_token" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::MagicAuthCodeSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["client_secret"], json[:client_secret]
    assert_equal fixture["code"], json[:code]
    assert_equal fixture["email"], json[:email]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_email_verification_code_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "client_secret" => "stub",
      "grant_type" => "urn:workos:oauth:grant-type:email-verification:code",
      "code" => "stub",
      "pending_authentication_token" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::EmailVerificationCodeSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["client_secret"], json[:client_secret]
    assert_equal fixture["code"], json[:code]
    assert_equal fixture["pending_authentication_token"], json[:pending_authentication_token]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_mfa_totp_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "client_secret" => "stub",
      "grant_type" => "urn:workos:oauth:grant-type:mfa-totp",
      "code" => "stub",
      "pending_authentication_token" => "stub",
      "authentication_challenge_id" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::MFATotpSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["client_secret"], json[:client_secret]
    assert_equal fixture["code"], json[:code]
    assert_equal fixture["pending_authentication_token"], json[:pending_authentication_token]
    assert_equal fixture["authentication_challenge_id"], json[:authentication_challenge_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_organization_selection_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "client_secret" => "stub",
      "grant_type" => "urn:workos:oauth:grant-type:organization-selection",
      "pending_authentication_token" => "stub",
      "organization_id" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::OrganizationSelectionSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["client_secret"], json[:client_secret]
    assert_equal fixture["pending_authentication_token"], json[:pending_authentication_token]
    assert_equal fixture["organization_id"], json[:organization_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_device_code_session_authenticate_request_round_trip
    fixture = {
      "client_id" => "stub",
      "grant_type" => "urn:ietf:params:oauth:grant-type:device_code",
      "device_code" => "stub",
      "ip_address" => "stub",
      "device_id" => "stub",
      "user_agent" => "stub"
    }
    model = WorkOS::DeviceCodeSessionAuthenticateRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    assert_equal fixture["device_code"], json[:device_code]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sso_device_authorization_request_round_trip
    fixture = {
      "client_id" => "stub"
    }
    model = WorkOS::SSODeviceAuthorizationRequest.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["client_id"], json[:client_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_invitation_round_trip
    fixture = {
      "object" => "invitation",
      "id" => "stub",
      "email" => "stub",
      "state" => "stub",
      "accepted_at" => nil,
      "revoked_at" => nil,
      "expires_at" => "stub",
      "organization_id" => nil,
      "inviter_user_id" => nil,
      "accepted_user_id" => nil,
      "role_slug" => nil,
      "created_at" => "stub",
      "updated_at" => "stub",
      "token" => "stub",
      "accept_invitation_url" => "stub"
    }
    model = WorkOS::Invitation.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_nil json[:accepted_at]
    assert_nil json[:revoked_at]
    assert_equal fixture["expires_at"], json[:expires_at]
    assert_nil json[:organization_id]
    assert_nil json[:inviter_user_id]
    assert_nil json[:accepted_user_id]
    assert_nil json[:role_slug]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    assert_equal fixture["token"], json[:token]
    assert_equal fixture["accept_invitation_url"], json[:accept_invitation_url]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_email_change_confirmation_round_trip
    fixture = {
      "object" => "email_change_confirmation",
      "user" => {}
    }
    model = WorkOS::EmailChangeConfirmation.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_email_change_confirmation_user_round_trip
    fixture = {
      "object" => "user",
      "id" => "stub",
      "first_name" => nil,
      "last_name" => nil,
      "name" => nil,
      "profile_picture_url" => nil,
      "email" => "stub",
      "email_verified" => true,
      "external_id" => nil,
      "metadata" => {},
      "last_sign_in_at" => nil,
      "locale" => nil,
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::EmailChangeConfirmationUser.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_nil json[:first_name]
    assert_nil json[:last_name]
    assert_nil json[:profile_picture_url]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["email_verified"], json[:email_verified]
    assert_nil json[:external_id]
    assert_nil json[:last_sign_in_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_identities_get_item_round_trip
    fixture = {
      "idp_id" => "stub",
      "type" => "OAuth",
      "provider" => "stub"
    }
    model = WorkOS::UserIdentitiesGetItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["idp_id"], json[:idp_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_sessions_list_item_round_trip
    fixture = {
      "object" => "session",
      "id" => "stub",
      "impersonator" => {},
      "ip_address" => nil,
      "organization_id" => "stub",
      "user_agent" => nil,
      "user_id" => "stub",
      "auth_method" => "stub",
      "status" => "stub",
      "expires_at" => "stub",
      "ended_at" => nil,
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::UserSessionsListItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_nil json[:ip_address]
    assert_nil json[:user_agent]
    assert_equal fixture["user_id"], json[:user_id]
    assert_equal fixture["expires_at"], json[:expires_at]
    assert_nil json[:ended_at]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_user_sessions_impersonator_round_trip
    fixture = {
      "email" => "stub",
      "reason" => nil
    }
    model = WorkOS::UserSessionsImpersonator.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["email"], json[:email]
    assert_nil json[:reason]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end
end
