# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class OrganizationDomainsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = WorkOS::Client.new(api_key: "sk_test_123")
  end

  def test_create_organization_domain_returns_expected_result
    stub_request(:post, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: "{}", status: 200)
    result = @client.organization_domains.create_organization_domain(domain: "stub", organization_id: "stub")
    refute_nil result
  end

  def test_create_organization_domain_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.organization_domains.create_organization_domain(domain: "stub", organization_id: "stub")
    end
  end

  def test_get_organization_domain_returns_expected_result
    stub_request(:get, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: "{}", status: 200)
    result = @client.organization_domains.get_organization_domain(id: "stub")
    refute_nil result
  end

  def test_get_organization_domain_raises_authentication_error_on_401
    stub_request(:get, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.organization_domains.get_organization_domain(id: "stub")
    end
  end

  def test_delete_organization_domain_returns_expected_result
    stub_request(:delete, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: "{}", status: 200)
    result = @client.organization_domains.delete_organization_domain(id: "stub")
    assert_nil result if result.nil?
  end

  def test_delete_organization_domain_raises_authentication_error_on_401
    stub_request(:delete, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.organization_domains.delete_organization_domain(id: "stub")
    end
  end

  def test_verify_organization_domain_returns_expected_result
    stub_request(:post, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: "{}", status: 200)
    result = @client.organization_domains.verify_organization_domain(id: "stub")
    refute_nil result
  end

  def test_verify_organization_domain_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("organization_domains")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.organization_domains.verify_organization_domain(id: "stub")
    end
  end
end
