# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class PipesProviderTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = WorkOS::Client.new(api_key: "sk_test_123")
  end

  def test_list_organization_data_integration_configurations_returns_expected_result
    stub_request(:get, %r{\Ahttps://api\.workos\.com/organizations/stub/data_integration_configurations(\?|\z)})
      .to_return(body: "{}", status: 200)
    result = @client.pipes_provider.list_organization_data_integration_configurations(organization_id: "stub")
    refute_nil result
  end

  def test_update_organization_data_integration_configuration_returns_expected_result
    stub_request(:put, %r{\Ahttps://api\.workos\.com/organizations/stub/data_integration_configurations/stub(\?|\z)})
      .to_return(body: "{}", status: 200)
    result = @client.pipes_provider.update_organization_data_integration_configuration(organization_id: "stub", slug: "stub")
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :list_organization_data_integration_configurations, verb: :get, url: %r{\Ahttps://api\.workos\.com/organizations/stub/data_integration_configurations(\?|\z)}, args: {organization_id: "stub"}},
    {name: :update_organization_data_integration_configuration, verb: :put, url: %r{\Ahttps://api\.workos\.com/organizations/stub/data_integration_configurations/stub(\?|\z)}, args: {organization_id: "stub", slug: "stub"}}
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(WorkOS::AuthenticationError) do
        @client.pipes_provider.send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
