# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class ConnectModelRoundTripTest < Minitest::Test
  def test_connect_application_round_trip
    fixture = {
      "object" => "connect_application",
      "id" => "stub",
      "client_id" => "stub",
      "description" => nil,
      "name" => "stub",
      "scopes" => [],
      "created_at" => "stub",
      "updated_at" => "stub"
    }
    model = WorkOS::ConnectApplication.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["client_id"], json[:client_id]
    assert_nil json[:description]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end
end
