# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class WidgetsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = WorkOS::Client.new(api_key: "sk_test_123")
  end

  def test_create_token_returns_expected_result
    stub_request(:post, /#{Regexp.escape("widgets")}/)
      .to_return(body: "{}", status: 200)
    result = @client.widgets.create_token(organization_id: "stub")
    refute_nil result
  end

  def test_create_token_raises_authentication_error_on_401
    stub_request(:post, /#{Regexp.escape("widgets")}/)
      .to_return(body: '{"message": "Unauthorized"}', status: 401)
    assert_raises(WorkOS::AuthenticationError) do
      @client.widgets.create_token(organization_id: "stub")
    end
  end
end
