inherit_from: .rubocop_todo.yml

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/LineLength:
  AllowedPatterns:
    - 'VCR\.use_cassette'
    - '(\A|\s)/.*?/'
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'before', 'it']
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
Naming/ConstantName:
  Exclude:
    - 'lib/workos/user_management.rb'
    - 'lib/workos/types/*.rb'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'consistent_comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
AllCops:
  TargetRubyVersion: 3.1
