# Disabling due to conflict with Ruby 2.7/3.1
Layout/BlockAlignment:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/LineLength:
  IgnoredPatterns:
    - 'VCR\.use_cassette'
    - '(\A|\s)/.*?/'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'before']
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 6
Naming/ConstantName:
  Exclude:
    - 'lib/workos/user_management.rb'
    - 'lib/workos/types/*.rb'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'consistent_comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
AllCops:
  TargetRubyVersion: 2.7
