Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/LineLength:
  IgnoredPatterns:
    - 'VCR\.use_cassette'
    - '(\A|\s)/.*?/'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'before']
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 6
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'consistent_comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
AllCops:
  TargetRubyVersion: 2.5
