# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class ApplicationCredentialsListItem < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      object: :object,
      id: :id,
      secret_hint: :secret_hint,
      last_used_at: :last_used_at,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :secret_hint,
      :last_used_at,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @secret_hint = hash[:secret_hint]
      @last_used_at = hash[:last_used_at]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
