# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class ConnectApplication
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :client_id,
      :description,
      :name,
      :scopes,
      :created_at,
      :updated_at,
      :application_type,
      :organization_id

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @client_id = hash[:client_id]
      @description = hash[:description]
      @name = hash[:name]
      @scopes = hash[:scopes] || []
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @application_type = hash[:application_type]
      @organization_id = hash[:organization_id]
    end

    def to_h
      {
        object: object,
        id: id,
        client_id: client_id,
        description: description,
        name: name,
        scopes: scopes,
        created_at: created_at,
        updated_at: updated_at,
        application_type: application_type,
        organization_id: organization_id
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end
  end
end
