# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class UpdateOAuthApplication
    include HashProvider

    attr_accessor \
      :name,
      :description,
      :scopes,
      :redirect_uris

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @name = hash[:name]
      @description = hash[:description]
      @scopes = hash[:scopes] || []
      @redirect_uris = (hash[:redirect_uris] || []).map { |item| item ? WorkOS::RedirectUriInput.new(item) : nil }
    end

    def to_h
      {
        name: name,
        description: description,
        scopes: scopes,
        redirect_uris: (redirect_uris || []).map(&:to_h)
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end
  end
end
