# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class UpdateOAuthApplication
    include HashProvider

    HASH_ATTRS = {
      name: :name,
      description: :description,
      scopes: :scopes,
      redirect_uris: :redirect_uris
    }.freeze

    attr_accessor \
      :name,
      :description,
      :scopes,
      :redirect_uris

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @name = hash[:name]
      @description = hash[:description]
      @scopes = hash[:scopes] || []
      @redirect_uris = (hash[:redirect_uris] || []).map { |item| item ? WorkOS::RedirectUriInput.new(item) : nil }
    end
  end
end
