# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class UserConsentOptionChoice < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      value: :value,
      label: :label
    }.freeze

    attr_accessor \
      :value,
      :label

    def initialize(json)
      hash = self.class.normalize(json)
      @value = hash[:value]
      @label = hash[:label]
    end
  end
end
