# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class UserManagementLoginRequest
    include HashProvider

    attr_accessor \
      :external_auth_id,
      :user,
      :user_consent_options

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @external_auth_id = hash[:external_auth_id]
      @user = hash[:user] ? WorkOS::UserObject.new(hash[:user].to_json) : nil
      @user_consent_options = (hash[:user_consent_options] || []).map { |item| item ? WorkOS::UserConsentOption.new(item.to_json) : nil }
    end

    def to_json(*)
      {
        external_auth_id: external_auth_id,
        user: user&.to_json,
        user_consent_options: (user_consent_options || []).map(&:to_json)
      }
    end
  end
end
