# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class DirectoryMetadata < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      users: :users,
      groups: :groups
    }.freeze

    attr_accessor \
      :users,
      :groups

    def initialize(json)
      hash = self.class.normalize(json)
      @users = hash[:users] ? WorkOS::DirectoryMetadataUser.new(hash[:users]) : nil
      @groups = hash[:groups]
    end
  end
end
