# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DirectoryUserEmail
    include HashProvider

    HASH_ATTRS = {
      primary: :primary,
      type: :type,
      value: :value
    }.freeze

    attr_accessor \
      :primary,
      :type,
      :value

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @primary = hash[:primary]
      @type = hash[:type]
      @value = hash[:value]
    end
  end
end
