# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DirectoryMetadata
    include HashProvider

    HASH_ATTRS = {
      users: :users,
      groups: :groups
    }.freeze

    attr_accessor \
      :users,
      :groups

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @users = hash[:users] ? WorkOS::DirectoryMetadataUser.new(hash[:users]) : nil
      @groups = hash[:groups]
    end
  end
end
