# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class DirectorySyncRateLimitError < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      code: :code,
      message: :message,
      retry_after_seconds: :retry_after_seconds
    }.freeze

    attr_accessor \
      :code,
      :message,
      :retry_after_seconds

    def initialize(json)
      hash = self.class.normalize(json)
      @code = hash[:code]
      @message = hash[:message]
      @retry_after_seconds = hash[:retry_after_seconds]
    end
  end
end
