# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class Directory < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      object: :object,
      id: :id,
      organization_id: :organization_id,
      external_key: :external_key,
      type: :type,
      state: :state,
      name: :name,
      domain: :domain,
      metadata: :metadata,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :organization_id,
      :external_key,
      :type,
      :state,
      :name,
      :domain,
      :metadata,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @organization_id = hash[:organization_id]
      @external_key = hash[:external_key]
      @type = hash[:type]
      @state = hash[:state]
      @name = hash[:name]
      @domain = hash[:domain]
      @metadata = hash[:metadata] ? WorkOS::DirectoryMetadata.new(hash[:metadata]) : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
