# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class DsyncTokenCreatedData < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      directory_id: :directory_id,
      organization_id: :organization_id,
      token_suffix: :token_suffix,
      created_at: :created_at,
      expires_at: :expires_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :directory_id,
      :organization_id,
      :token_suffix,
      :created_at,
      :expires_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @directory_id = hash[:directory_id]
      @organization_id = hash[:organization_id]
      @token_suffix = hash[:token_suffix]
      @created_at = hash[:created_at]
      @expires_at = hash[:expires_at]
    end
  end
end
