# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DsyncGroupUserAddedData
    include HashProvider

    attr_accessor \
      :directory_id,
      :user,
      :group

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @directory_id = hash[:directory_id]
      @user = hash[:user] ? WorkOS::DirectoryUser.new(hash[:user].to_json) : nil
      @group = hash[:group] ? WorkOS::DirectoryGroup.new(hash[:group].to_json) : nil
    end

    def to_json(*)
      {
        directory_id: directory_id,
        user: user&.to_json,
        group: group&.to_json
      }
    end
  end
end
