# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class FeatureFlagOwner < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      email: :email,
      first_name: :first_name,
      last_name: :last_name
    }.freeze

    attr_accessor \
      :email,
      :first_name,
      :last_name

    def initialize(json)
      hash = self.class.normalize(json)
      @email = hash[:email]
      @first_name = hash[:first_name]
      @last_name = hash[:last_name]
    end
  end
end
