# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class FlagRuleUpdatedContextConfiguredTargetUser
    include HashProvider

    attr_accessor \
      :id,
      :email

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @id = hash[:id]
      @email = hash[:email]
    end

    def to_h
      {
        id: id,
        email: email
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

    def inspect
      "#<#{self.class} id=#{@id}>"
    end
  end
end
