# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class FlagUpdatedContext
    include HashProvider

    attr_accessor \
      :client_id,
      :actor,
      :previous_attributes

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @client_id = hash[:client_id]
      @actor = hash[:actor] ? WorkOS::FlagUpdatedContextActor.new(hash[:actor]) : nil
      @previous_attributes = hash[:previous_attributes] ? WorkOS::FlagUpdatedContextPreviousAttribute.new(hash[:previous_attributes]) : nil
    end

    def to_h
      {
        client_id: client_id,
        actor: actor&.to_h,
        previous_attributes: previous_attributes&.to_h
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end
  end
end
