# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class FlagRuleUpdatedContextConfiguredTargetUser < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      email: :email
    }.freeze

    attr_accessor \
      :id,
      :email

    def initialize(json)
      hash = self.class.normalize(json)
      @id = hash[:id]
      @email = hash[:email]
    end
  end
end
