# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class FlagUpdatedContextPreviousAttribute < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      data: :data
    }.freeze

    attr_accessor :data

    def initialize(json)
      hash = self.class.normalize(json)
      @data = hash[:data] ? WorkOS::FlagUpdatedContextPreviousAttributeData.new(hash[:data]) : nil
    end
  end
end
