# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class FlagRuleUpdatedContext < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      client_id: :client_id,
      actor: :actor,
      access_type: :access_type,
      configured_targets: :configured_targets,
      previous_attributes: :previous_attributes
    }.freeze

    attr_accessor \
      :client_id,
      :actor,
      :access_type,
      :configured_targets,
      :previous_attributes

    def initialize(json)
      hash = self.class.normalize(json)
      @client_id = hash[:client_id]
      @actor = hash[:actor] ? WorkOS::FlagRuleUpdatedContextActor.new(hash[:actor]) : nil
      @access_type = hash[:access_type]
      @configured_targets = hash[:configured_targets] ? WorkOS::FlagRuleUpdatedContextConfiguredTarget.new(hash[:configured_targets]) : nil
      @previous_attributes = hash[:previous_attributes] ? WorkOS::FlagRuleUpdatedContextPreviousAttribute.new(hash[:previous_attributes]) : nil
    end
  end
end
