# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class FlagRuleUpdatedContextPreviousAttributeContext < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      access_type: :access_type,
      configured_targets: :configured_targets
    }.freeze

    attr_accessor \
      :access_type,
      :configured_targets

    def initialize(json)
      hash = self.class.normalize(json)
      @access_type = hash[:access_type]
      @configured_targets = hash[:configured_targets] ? WorkOS::FlagRuleUpdatedContextPreviousAttributeContextConfiguredTarget.new(hash[:configured_targets]) : nil
    end
  end
end
