# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class ConnectionDeletedData < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      object: :object,
      id: :id,
      state: :state,
      name: :name,
      connection_type: :connection_type,
      organization_id: :organization_id,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :state,
      :name,
      :connection_type,
      :organization_id,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @state = hash[:state]
      @name = hash[:name]
      @connection_type = hash[:connection_type]
      @organization_id = hash[:organization_id]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
