# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class PatchConnectionSAMLOptions < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      idp_metadata_url: :idp_metadata_url,
      acs_url: :acs_url,
      sp_entity_id: :sp_entity_id,
      idp_entity_id: :idp_entity_id,
      idp_sso_url: :idp_sso_url
    }.freeze

    attr_accessor \
      :idp_metadata_url,
      :acs_url,
      :sp_entity_id,
      :idp_entity_id,
      :idp_sso_url

    def initialize(json)
      hash = self.class.normalize(json)
      @idp_metadata_url = hash[:idp_metadata_url]
      @acs_url = hash[:acs_url]
      @sp_entity_id = hash[:sp_entity_id]
      @idp_entity_id = hash[:idp_entity_id]
      @idp_sso_url = hash[:idp_sso_url]
    end
  end
end
