# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class SSOTokenResponse < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      token_type: :token_type,
      access_token: :access_token,
      expires_in: :expires_in,
      profile: :profile,
      oauth_tokens: :oauth_tokens
    }.freeze

    attr_accessor \
      :token_type,
      :access_token,
      :expires_in,
      :profile,
      :oauth_tokens

    def initialize(json)
      hash = self.class.normalize(json)
      @token_type = hash[:token_type]
      @access_token = hash[:access_token]
      @expires_in = hash[:expires_in]
      @profile = hash[:profile] ? WorkOS::Profile.new(hash[:profile]) : nil
      @oauth_tokens = hash[:oauth_tokens] ? WorkOS::SSOTokenResponseOAuthToken.new(hash[:oauth_tokens]) : nil
    end
  end
end
