# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class TokenQuery < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      client_id: :client_id,
      client_secret: :client_secret,
      code: :code,
      grant_type: :grant_type
    }.freeze

    attr_accessor \
      :client_id,
      :client_secret,
      :code,
      :grant_type

    def initialize(json)
      hash = self.class.normalize(json)
      @client_id = hash[:client_id]
      @client_secret = hash[:client_secret]
      @code = hash[:code]
      @grant_type = hash[:grant_type]
    end
  end
end
