# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class AuthenticationFactorsCreateRequestType
      GENERIC_OTP = "generic_otp"
      SMS = "sms"
      TOTP = "totp"
      ALL = [GENERIC_OTP, SMS, TOTP].freeze
    end
  end
end
