# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class AuthenticateResponseAuthenticationMethod
      SSO = 'SSO'
      PASSWORD = 'Password'
      PASSKEY = 'Passkey'
      APPLE_OAUTH = 'AppleOAuth'
      BITBUCKET_OAUTH = 'BitbucketOAuth'
      CROSS_APP_AUTH = 'CrossAppAuth'
      DISCORD_OAUTH = 'DiscordOAuth'
      EXTERNAL_AUTH = 'ExternalAuth'
      GIT_HUB_OAUTH = 'GitHubOAuth'
      GIT_LAB_OAUTH = 'GitLabOAuth'
      GOOGLE_OAUTH = 'GoogleOAuth'
      INTUIT_OAUTH = 'IntuitOAuth'
      LINKED_IN_OAUTH = 'LinkedInOAuth'
      MICROSOFT_OAUTH = 'MicrosoftOAuth'
      SALESFORCE_OAUTH = 'SalesforceOAuth'
      SLACK_OAUTH = 'SlackOAuth'
      VERCEL_MARKETPLACE_OAUTH = 'VercelMarketplaceOAuth'
      VERCEL_OAUTH = 'VercelOAuth'
      XERO_OAUTH = 'XeroOAuth'
      MAGIC_AUTH = 'MagicAuth'
      IMPERSONATION = 'Impersonation'
      MIGRATED_SESSION = 'MigratedSession'
      ALL = [SSO, PASSWORD, PASSKEY, APPLE_OAUTH, BITBUCKET_OAUTH, CROSS_APP_AUTH, DISCORD_OAUTH, EXTERNAL_AUTH, GIT_HUB_OAUTH, GIT_LAB_OAUTH, GOOGLE_OAUTH, INTUIT_OAUTH, LINKED_IN_OAUTH, MICROSOFT_OAUTH, SALESFORCE_OAUTH, SLACK_OAUTH, VERCEL_MARKETPLACE_OAUTH, VERCEL_OAUTH, XERO_OAUTH, MAGIC_AUTH, IMPERSONATION, MIGRATED_SESSION].freeze
    end
  end
end
