# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    ConnectionSAMLCertificateRenewedDataCertificateCertificateType = ConnectionSAMLCertificateRenewalRequiredDataCertificateCertificateType
  end
end
