# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class ConnectedAccountState
      CONNECTED = "connected"
      NEEDS_REAUTHORIZATION = "needs_reauthorization"
      DISCONNECTED = "disconnected"
      ALL = [CONNECTED, NEEDS_REAUTHORIZATION, DISCONNECTED].freeze
    end
  end
end
