# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class ConnectionSAMLCertificateRenewalRequiredDataCertificateCertificateType
      RESPONSE_SIGNING = "ResponseSigning"
      REQUEST_SIGNING = "RequestSigning"
      RESPONSE_ENCRYPTION = "ResponseEncryption"
      ALL = [RESPONSE_SIGNING, REQUEST_SIGNING, RESPONSE_ENCRYPTION].freeze
    end
  end
end
