# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class CreateConnectionOIDCOptionsTokenAuthenticationMethod
      CLIENT_SECRET_POST = "client_secret_post"
      CLIENT_SECRET_BASIC = "client_secret_basic"
      PRIVATE_KEY_JWT = "private_key_jwt"
      ALL = [CLIENT_SECRET_POST, CLIENT_SECRET_BASIC, PRIVATE_KEY_JWT].freeze
    end
  end
end
