# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class DataIntegrationCredentialsCredentialsType
      SHARED = "shared"
      CUSTOM = "custom"
      ORGANIZATION = "organization"
      ALL = [SHARED, CUSTOM, ORGANIZATION].freeze
    end
  end
end
