# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    DataIntegrationsGetUserTokenRequestConnectionOwner = CreateDataIntegrationOwnership
  end
end
