# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class DirectoryState
      LINKED = "linked"
      VALIDATING = "validating"
      INVALID_CREDENTIALS = "invalid_credentials"
      UNLINKED = "unlinked"
      DELETING = "deleting"
      ALL = [LINKED, VALIDATING, INVALID_CREDENTIALS, UNLINKED, DELETING].freeze
    end
  end
end
