# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class FlagRuleUpdatedContextAccessType
      NONE = 'none'
      SOME = 'some'
      VALUE_ALL = 'all'
      ALL = [NONE, SOME, VALUE_ALL].freeze
    end
  end
end
