# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class OrganizationMembershipStatus
      ACTIVE = "active"
      INACTIVE = "inactive"
      PENDING = "pending"
      ALL = [ACTIVE, INACTIVE, PENDING].freeze
    end
  end
end
