# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class OrganizationCreatedDataDomainState
      FAILED = 'failed'
      LEGACY_VERIFIED = 'legacy_verified'
      PENDING = 'pending'
      UNVERIFIED = 'unverified'
      VERIFIED = 'verified'
      ALL = [FAILED, LEGACY_VERIFIED, PENDING, UNVERIFIED, VERIFIED].freeze
    end
  end
end
