# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    OrganizationDomainVerificationFailedDataOrganizationDomainVerificationStrategy = OrganizationCreatedDataDomainVerificationStrategy
  end
end
