# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    OrganizationDomainVerifiedDataVerificationStrategy = OrganizationCreatedDataDomainVerificationStrategy
  end
end
