# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class RadarListAction
      BLOCK = "block"
      ALLOW = "allow"
      ALL = [BLOCK, ALLOW].freeze
    end
  end
end
