# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class RadarStandaloneResponseBlocklistType
      IP_ADDRESS = "ip_address"
      DOMAIN = "domain"
      EMAIL = "email"
      DEVICE = "device"
      USER_AGENT = "user_agent"
      DEVICE_FINGERPRINT = "device_fingerprint"
      COUNTRY = "country"
      ALL = [IP_ADDRESS, DOMAIN, EMAIL, DEVICE, USER_AGENT, DEVICE_FINGERPRINT, COUNTRY].freeze
    end
  end
end
