# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class SSOGrantType
      AUTHORIZATION_CODE = "authorization_code"
      URN_IETF_PARAMS_OAUTH_GRANT_TYPE_TOKEN_EXCHANGE = "urn:ietf:params:oauth:grant-type:token-exchange"
      ALL = [AUTHORIZATION_CODE, URN_IETF_PARAMS_OAUTH_GRANT_TYPE_TOKEN_EXCHANGE].freeze
    end
  end
end
