# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class UpdateWebhookEndpointStatus
      ENABLED = 'enabled'
      DISABLED = 'disabled'
      ALL = [ENABLED, DISABLED].freeze
    end
  end
end
