# This file is auto-generated by oagen. Do not edit.

module WorkOS
  module Types
    class UserManagementAuthenticationScreenHint
      SIGN_UP = "sign-up"
      SIGN_IN = "sign-in"
      ALL = [SIGN_UP, SIGN_IN].freeze
    end
  end
end
