# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class AuthorizationResource
    include HashProvider

    HASH_ATTRS = {
      object: :object,
      name: :name,
      description: :description,
      organization_id: :organization_id,
      parent_resource_id: :parent_resource_id,
      id: :id,
      external_id: :external_id,
      resource_type_slug: :resource_type_slug,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :name,
      :description,
      :organization_id,
      :parent_resource_id,
      :id,
      :external_id,
      :resource_type_slug,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @name = hash[:name]
      @description = hash[:description]
      @organization_id = hash[:organization_id]
      @parent_resource_id = hash[:parent_resource_id]
      @id = hash[:id]
      @external_id = hash[:external_id]
      @resource_type_slug = hash[:resource_type_slug]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
