# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class CheckAuthorization
    include HashProvider

    attr_accessor :permission_slug

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @permission_slug = hash[:permission_slug]
    end

    def to_h
      {
        permission_slug: permission_slug
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end
  end
end
