# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class CheckAuthorization < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      permission_slug: :permission_slug,
      resource_id: :resource_id,
      resource_external_id: :resource_external_id,
      resource_type_slug: :resource_type_slug
    }.freeze

    attr_accessor \
      :permission_slug,
      :resource_id,
      :resource_external_id,
      :resource_type_slug

    def initialize(json)
      hash = self.class.normalize(json)
      @permission_slug = hash[:permission_slug]
      @resource_id = hash[:resource_id]
      @resource_external_id = hash[:resource_external_id]
      @resource_type_slug = hash[:resource_type_slug]
    end
  end
end
