# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class ReplaceGroupRoleAssignments < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      role_assignments: :role_assignments
    }.freeze

    attr_accessor :role_assignments

    def initialize(json)
      hash = self.class.normalize(json)
      @role_assignments = (hash[:role_assignments] || []).map { |item| item ? WorkOS::ReplaceGroupRoleAssignmentEntry.new(item) : nil }
    end
  end
end
