# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class RoleAssignment
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :role,
      :resource,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @role = hash[:role] ? WorkOS::SlimRole.new(hash[:role]) : nil
      @resource = hash[:resource] ? WorkOS::RoleAssignmentResource.new(hash[:resource]) : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end

    def to_h
      {
        object: object,
        id: id,
        role: role&.to_h,
        resource: resource&.to_h,
        created_at: created_at,
        updated_at: updated_at
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

    def inspect
      "#<#{self.class} id=#{@id}>"
    end
  end
end
