# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class SetRolePermissions < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      permissions: :permissions
    }.freeze

    attr_accessor :permissions

    def initialize(json)
      hash = self.class.normalize(json)
      @permissions = (hash[:permissions] || [])
    end
  end
end
