# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class UpdateAuthorizationResource
    include HashProvider

    HASH_ATTRS = {
      name: :name,
      description: :description,
      parent_resource_id: :parent_resource_id,
      parent_resource_external_id: :parent_resource_external_id,
      parent_resource_type_slug: :parent_resource_type_slug
    }.freeze

    attr_accessor \
      :name,
      :description,
      :parent_resource_id,
      :parent_resource_external_id,
      :parent_resource_type_slug

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @name = hash[:name]
      @description = hash[:description]
      @parent_resource_id = hash[:parent_resource_id]
      @parent_resource_external_id = hash[:parent_resource_external_id]
      @parent_resource_type_slug = hash[:parent_resource_type_slug]
    end
  end
end
