# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class UpdateAuthorizationPermission
    include HashProvider

    attr_accessor \
      :name,
      :description

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @name = hash[:name]
      @description = hash[:description]
    end

    def to_json(*)
      {
        name: name,
        description: description
      }
    end
  end
end
