# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class Authorization
    def initialize(client)
      @client = client
    end

    # Check authorization
    # @param organization_membership_id [String] The ID of the organization membership to check.
    # @param permission_slug [String] The slug of the permission to check.
    # @param resource_id [String, nil] The ID of the resource.
    # @param resource_external_id [String, nil] The external ID of the resource.
    # @param resource_type_slug [String, nil] The slug of the resource type.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationCheck]
    def check(
      organization_membership_id:,
      permission_slug:,
      resource_id: nil,
      resource_external_id: nil,
      resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "permission_slug" => permission_slug,
        "resource_id" => resource_id,
        "resource_external_id" => resource_external_id,
        "resource_type_slug" => resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/organization_memberships/#{organization_membership_id}/check", auth: true, body: body)
      )
      WorkOS::AuthorizationCheck.new(response.body)
    end

    # List resources for organization membership
    # @param organization_membership_id [String] The ID of the organization membership.
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::AuthorizationOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param permission_slug [String] The permission slug to filter by. Only child resources where the organization membership has this permission are returned.
    # @param parent_resource_id [String, nil] The WorkOS ID of the parent resource. Provide this or both `parent_resource_external_id` and `parent_resource_type_slug`, but not both.
    # @param parent_resource_type_slug [String, nil] The slug of the parent resource type. Must be provided together with `parent_resource_external_id`.
    # @param parent_resource_external_id [String, nil] The application-specific external identifier of the parent resource. Must be provided together with `parent_resource_type_slug`.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationResourceList]
    def list_organization_membership_resources(
      organization_membership_id:,
      permission_slug:,
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      parent_resource_id: nil,
      parent_resource_type_slug: nil,
      parent_resource_external_id: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "permission_slug" => permission_slug,
        "parent_resource_id" => parent_resource_id,
        "parent_resource_type_slug" => parent_resource_type_slug,
        "parent_resource_external_id" => parent_resource_external_id
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/organization_memberships/#{organization_membership_id}/resources", auth: true, params: params)
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::AuthorizationResource.new(item.to_json) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["before"] || metadata[:before]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_organization_membership_resources(
          organization_membership_id: organization_membership_id,
          before: cursor,
          after: after,
          limit: limit,
          order: order,
          permission_slug: permission_slug,
          parent_resource_id: parent_resource_id,
          parent_resource_type_slug: parent_resource_type_slug,
          parent_resource_external_id: parent_resource_external_id,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next)
    end

    # List role assignments
    # @param organization_membership_id [String] The ID of the organization membership.
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::AuthorizationOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::RoleAssignmentList]
    def list_organization_membership_role_assignments(
      organization_membership_id:,
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/organization_memberships/#{organization_membership_id}/role_assignments", auth: true, params: params)
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::RoleAssignment.new(item.to_json) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["before"] || metadata[:before]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_organization_membership_role_assignments(
          organization_membership_id: organization_membership_id,
          before: cursor,
          after: after,
          limit: limit,
          order: order,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next)
    end

    # Assign a role
    # @param organization_membership_id [String] The ID of the organization membership.
    # @param role_slug [String] The slug of the role to assign.
    # @param resource_id [String, nil] The ID of the resource. Use either this or `resource_external_id` and `resource_type_slug`.
    # @param resource_external_id [String, nil] The external ID of the resource. Requires `resource_type_slug`.
    # @param resource_type_slug [String, nil] The resource type slug. Required with `resource_external_id`.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::RoleAssignment]
    def assign_role(
      organization_membership_id:,
      role_slug:,
      resource_id: nil,
      resource_external_id: nil,
      resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "role_slug" => role_slug,
        "resource_id" => resource_id,
        "resource_external_id" => resource_external_id,
        "resource_type_slug" => resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/organization_memberships/#{organization_membership_id}/role_assignments", auth: true, body: body)
      )
      WorkOS::RoleAssignment.new(response.body)
    end

    # Remove a role assignment
    # @param organization_membership_id [String] The ID of the organization membership.
    # @param role_slug [String] The slug of the role to remove.
    # @param resource_id [String, nil] The ID of the resource. Use either this or `resource_external_id` and `resource_type_slug`.
    # @param resource_external_id [String, nil] The external ID of the resource. Requires `resource_type_slug`.
    # @param resource_type_slug [String, nil] The resource type slug. Required with `resource_external_id`.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [Object]
    def remove_role(
      organization_membership_id:,
      role_slug:,
      resource_id: nil,
      resource_external_id: nil,
      resource_type_slug: nil,
      request_options: {}
    )
      @client.execute_request(
        request: @client.delete_request(path: "/authorization/organization_memberships/#{organization_membership_id}/role_assignments", auth: true)
      )
      nil
    end

    # Remove a role assignment by ID
    # @param organization_membership_id [String] The ID of the organization membership.
    # @param role_assignment_id [String] The ID of the role assignment to remove.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [Object]
    def delete_organization_membership_role_assignment(
      organization_membership_id:,
      role_assignment_id:,
      request_options: {}
    )
      @client.execute_request(
        request: @client.delete_request(path: "/authorization/organization_memberships/#{organization_membership_id}/role_assignments/#{role_assignment_id}", auth: true)
      )
      nil
    end

    # List organization roles
    # @param organization_id [String] The ID of the organization.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::RoleList]
    def list_organization_roles(
      organization_id:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/organizations/#{organization_id}/roles", auth: true)
      )
      WorkOS::RoleList.new(response.body)
    end

    # Create a custom organization role
    # @param organization_id [String] The ID of the organization.
    # @param slug [String, nil] A unique identifier for the role within the organization. When provided, must begin with 'org-' and contain only lowercase letters, numbers, hyphens, and underscores. When omitted, a slug is auto-generated from the role name and a random suffix.
    # @param name [String] A descriptive name for the role.
    # @param description [String, nil, nil] An optional description of the role's purpose.
    # @param resource_type_slug [String, nil] The slug of the resource type the role is scoped to.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def create_organization_role(
      organization_id:,
      name:,
      slug: nil,
      description: nil,
      resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "slug" => slug,
        "name" => name,
        "description" => description,
        "resource_type_slug" => resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/organizations/#{organization_id}/roles", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # Get an organization role
    # @param organization_id [String] The ID of the organization.
    # @param slug [String] The slug of the role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def get_organization_role(
      organization_id:,
      slug:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/organizations/#{organization_id}/roles/#{slug}", auth: true)
      )
      WorkOS::Role.new(response.body)
    end

    # Update an organization role
    # @param organization_id [String] The ID of the organization.
    # @param slug [String] The slug of the role.
    # @param name [String, nil] A descriptive name for the role.
    # @param description [String, nil, nil] An optional description of the role's purpose.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def update_organization_role(
      organization_id:,
      slug:,
      name: nil,
      description: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "description" => description
      }.compact
      response = @client.execute_request(
        request: @client.patch_request(path: "/authorization/organizations/#{organization_id}/roles/#{slug}", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # Delete a custom organization role
    # @param organization_id [String] The ID of the organization.
    # @param slug [String] The slug of the role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [Object]
    def delete_organization_role(
      organization_id:,
      slug:,
      request_options: {}
    )
      @client.execute_request(
        request: @client.delete_request(path: "/authorization/organizations/#{organization_id}/roles/#{slug}", auth: true)
      )
      nil
    end

    # Add a permission to an organization role
    # @param organization_id [String] The ID of the organization.
    # @param slug [String] The slug of the role.
    # @param slug [String] The slug of the permission to add to the role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def create_role_permission(
      organization_id:,
      slug:,
      request_options: {}
    )
      body = {
        "slug" => slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/organizations/#{organization_id}/roles/#{slug}/permissions", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # Set permissions for a role
    # @param organization_id [String] The ID of the organization.
    # @param slug [String] The slug of the role.
    # @param permissions [Array<String>] The permission slugs to assign to the role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def update_role_permissions(
      organization_id:,
      slug:,
      permissions:,
      request_options: {}
    )
      body = {
        "permissions" => permissions
      }.compact
      response = @client.execute_request(
        request: @client.put_request(path: "/authorization/organizations/#{organization_id}/roles/#{slug}/permissions", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # Remove a permission from an organization role
    # @param organization_id [String] The ID of the organization.
    # @param slug [String] The slug of the role.
    # @param permission_slug [String] The slug of the permission to remove.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def delete_role_permission(
      organization_id:,
      slug:,
      permission_slug:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.delete_request(path: "/authorization/organizations/#{organization_id}/roles/#{slug}/permissions/#{permission_slug}", auth: true)
      )
      WorkOS::Role.new(response.body)
    end

    # Get a resource by external ID
    # @param organization_id [String] The ID of the organization that owns the resource.
    # @param resource_type_slug [String] The slug of the resource type.
    # @param external_id [String] An identifier you provide to reference the resource in your system.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationResource]
    def get_organization_resource(
      organization_id:,
      resource_type_slug:,
      external_id:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/organizations/#{organization_id}/resources/#{resource_type_slug}/#{external_id}", auth: true)
      )
      WorkOS::AuthorizationResource.new(response.body)
    end

    # Update a resource by external ID
    # @param organization_id [String] The ID of the organization that owns the resource.
    # @param resource_type_slug [String] The slug of the resource type.
    # @param external_id [String] An identifier you provide to reference the resource in your system.
    # @param name [String, nil] A display name for the resource.
    # @param description [String, nil, nil] An optional description of the resource.
    # @param parent_resource_id [String, nil] The ID of the parent resource.
    # @param parent_resource_external_id [String, nil] The external ID of the parent resource.
    # @param parent_resource_type_slug [String, nil] The resource type slug of the parent resource.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationResource]
    def update_organization_resource(
      organization_id:,
      resource_type_slug:,
      external_id:,
      name: nil,
      description: nil,
      parent_resource_id: nil,
      parent_resource_external_id: nil,
      parent_resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "description" => description,
        "parent_resource_id" => parent_resource_id,
        "parent_resource_external_id" => parent_resource_external_id,
        "parent_resource_type_slug" => parent_resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.patch_request(path: "/authorization/organizations/#{organization_id}/resources/#{resource_type_slug}/#{external_id}", auth: true, body: body)
      )
      WorkOS::AuthorizationResource.new(response.body)
    end

    # Delete an authorization resource by external ID
    # @param organization_id [String] The ID of the organization that owns the resource.
    # @param resource_type_slug [String] The slug of the resource type.
    # @param external_id [String] An identifier you provide to reference the resource in your system.
    # @param cascade_delete [Boolean, nil] If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [Object]
    def delete_organization_resource(
      organization_id:,
      resource_type_slug:,
      external_id:,
      cascade_delete: nil,
      request_options: {}
    )
      params = {
        "cascade_delete" => cascade_delete
      }.compact
      @client.execute_request(
        request: @client.delete_request(path: "/authorization/organizations/#{organization_id}/resources/#{resource_type_slug}/#{external_id}", auth: true, params: params)
      )
      nil
    end

    # List memberships for a resource by external ID
    # @param organization_id [String] The ID of the organization that owns the resource.
    # @param resource_type_slug [String] The slug of the resource type this resource belongs to.
    # @param external_id [String] An identifier you provide to reference the resource in your system.
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::AuthorizationOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param permission_slug [String] The permission slug to filter by. Only users with this permission on the resource are returned.
    # @param assignment [WorkOS::Types::AuthorizationAssignment, nil] Filter by assignment type. Use "direct" for direct assignments only, or "indirect" to include inherited assignments.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::UserOrganizationMembershipBaseList]
    def list_resource_organization_memberships(
      organization_id:,
      resource_type_slug:,
      external_id:,
      permission_slug:,
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      assignment: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "permission_slug" => permission_slug,
        "assignment" => assignment
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/organizations/#{organization_id}/resources/#{resource_type_slug}/#{external_id}/organization_memberships", auth: true, params: params)
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::UserOrganizationMembershipBaseListData.new(item.to_json) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["before"] || metadata[:before]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_resource_organization_memberships(
          organization_id: organization_id,
          resource_type_slug: resource_type_slug,
          external_id: external_id,
          before: cursor,
          after: after,
          limit: limit,
          order: order,
          permission_slug: permission_slug,
          assignment: assignment,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next)
    end

    # List resources
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::AuthorizationOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param organization_id [String, nil] Filter resources by organization ID.
    # @param resource_type_slug [String, nil] Filter resources by resource type slug.
    # @param parent_resource_id [String, nil] Filter resources by parent resource ID.
    # @param parent_resource_type_slug [String, nil] Filter resources by parent resource type slug.
    # @param parent_external_id [String, nil] Filter resources by parent external ID.
    # @param search [String, nil] Search resources by name.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationResourceList]
    def list_resources(
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      organization_id: nil,
      resource_type_slug: nil,
      parent_resource_id: nil,
      parent_resource_type_slug: nil,
      parent_external_id: nil,
      search: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "organization_id" => organization_id,
        "resource_type_slug" => resource_type_slug,
        "parent_resource_id" => parent_resource_id,
        "parent_resource_type_slug" => parent_resource_type_slug,
        "parent_external_id" => parent_external_id,
        "search" => search
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/resources", auth: true, params: params)
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::AuthorizationResource.new(item.to_json) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["before"] || metadata[:before]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_resources(
          before: cursor,
          after: after,
          limit: limit,
          order: order,
          organization_id: organization_id,
          resource_type_slug: resource_type_slug,
          parent_resource_id: parent_resource_id,
          parent_resource_type_slug: parent_resource_type_slug,
          parent_external_id: parent_external_id,
          search: search,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next)
    end

    # Create an authorization resource
    # @param external_id [String] An external identifier for the resource.
    # @param name [String] A display name for the resource.
    # @param description [String, nil, nil] An optional description of the resource.
    # @param resource_type_slug [String] The slug of the resource type.
    # @param organization_id [String] The ID of the organization this resource belongs to.
    # @param parent_resource_id [String, nil, nil] The ID of the parent resource.
    # @param parent_resource_external_id [String, nil] The external ID of the parent resource.
    # @param parent_resource_type_slug [String, nil] The resource type slug of the parent resource.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationResource]
    def create_resource(
      external_id:,
      name:,
      resource_type_slug:,
      organization_id:,
      description: nil,
      parent_resource_id: nil,
      parent_resource_external_id: nil,
      parent_resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "external_id" => external_id,
        "name" => name,
        "description" => description,
        "resource_type_slug" => resource_type_slug,
        "organization_id" => organization_id,
        "parent_resource_id" => parent_resource_id,
        "parent_resource_external_id" => parent_resource_external_id,
        "parent_resource_type_slug" => parent_resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/resources", auth: true, body: body)
      )
      WorkOS::AuthorizationResource.new(response.body)
    end

    # Get a resource
    # @param resource_id [String] The ID of the authorization resource.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationResource]
    def get_resource(
      resource_id:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/resources/#{resource_id}", auth: true)
      )
      WorkOS::AuthorizationResource.new(response.body)
    end

    # Update a resource
    # @param resource_id [String] The ID of the authorization resource.
    # @param name [String, nil] A display name for the resource.
    # @param description [String, nil, nil] An optional description of the resource.
    # @param parent_resource_id [String, nil] The ID of the parent resource.
    # @param parent_resource_external_id [String, nil] The external ID of the parent resource.
    # @param parent_resource_type_slug [String, nil] The resource type slug of the parent resource.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationResource]
    def update_resource(
      resource_id:,
      name: nil,
      description: nil,
      parent_resource_id: nil,
      parent_resource_external_id: nil,
      parent_resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "description" => description,
        "parent_resource_id" => parent_resource_id,
        "parent_resource_external_id" => parent_resource_external_id,
        "parent_resource_type_slug" => parent_resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.patch_request(path: "/authorization/resources/#{resource_id}", auth: true, body: body)
      )
      WorkOS::AuthorizationResource.new(response.body)
    end

    # Delete an authorization resource
    # @param resource_id [String] The ID of the authorization resource.
    # @param cascade_delete [Boolean, nil] If true, deletes all descendant resources and role assignments. If not set and the resource has children or assignments, the request will fail.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [Object]
    def delete_resource(
      resource_id:,
      cascade_delete: nil,
      request_options: {}
    )
      params = {
        "cascade_delete" => cascade_delete
      }.compact
      @client.execute_request(
        request: @client.delete_request(path: "/authorization/resources/#{resource_id}", auth: true, params: params)
      )
      nil
    end

    # List organization memberships for resource
    # @param resource_id [String] The ID of the authorization resource.
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::AuthorizationOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param permission_slug [String] The permission slug to filter by. Only users with this permission on the resource are returned.
    # @param assignment [WorkOS::Types::AuthorizationAssignment, nil] Filter by assignment type. Use `direct` for direct assignments only, or `indirect` to include inherited assignments.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::UserOrganizationMembershipBaseList]
    def list_memberships_for_resource(
      resource_id:,
      permission_slug:,
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      assignment: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "permission_slug" => permission_slug,
        "assignment" => assignment
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/resources/#{resource_id}/organization_memberships", auth: true, params: params)
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::UserOrganizationMembershipBaseListData.new(item.to_json) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["before"] || metadata[:before]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_memberships_for_resource(
          resource_id: resource_id,
          before: cursor,
          after: after,
          limit: limit,
          order: order,
          permission_slug: permission_slug,
          assignment: assignment,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next)
    end

    # List environment roles
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::RoleList]
    def list_environment_roles(request_options: {})
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/roles", auth: true)
      )
      WorkOS::RoleList.new(response.body)
    end

    # Create an environment role
    # @param slug [String] A unique slug for the role.
    # @param name [String] A descriptive name for the role.
    # @param description [String, nil, nil] An optional description of the role.
    # @param resource_type_slug [String, nil] The slug of the resource type the role is scoped to.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def create_environment_role(
      slug:,
      name:,
      description: nil,
      resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "slug" => slug,
        "name" => name,
        "description" => description,
        "resource_type_slug" => resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/roles", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # Get an environment role
    # @param slug [String] The slug of the environment role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def get_environment_role(
      slug:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/roles/#{slug}", auth: true)
      )
      WorkOS::Role.new(response.body)
    end

    # Update an environment role
    # @param slug [String] The slug of the environment role.
    # @param name [String, nil] A descriptive name for the role.
    # @param description [String, nil, nil] An optional description of the role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def update_environment_role(
      slug:,
      name: nil,
      description: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "description" => description
      }.compact
      response = @client.execute_request(
        request: @client.patch_request(path: "/authorization/roles/#{slug}", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # Add a permission to an environment role
    # @param slug [String] The slug of the environment role.
    # @param slug [String] The slug of the permission to add to the role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def add_environment_role_permission(
      slug:,
      request_options: {}
    )
      body = {
        "slug" => slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/roles/#{slug}/permissions", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # Set permissions for an environment role
    # @param slug [String] The slug of the environment role.
    # @param permissions [Array<String>] The permission slugs to assign to the role.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Role]
    def set_environment_role_permissions(
      slug:,
      permissions:,
      request_options: {}
    )
      body = {
        "permissions" => permissions
      }.compact
      response = @client.execute_request(
        request: @client.put_request(path: "/authorization/roles/#{slug}/permissions", auth: true, body: body)
      )
      WorkOS::Role.new(response.body)
    end

    # List permissions
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::PermissionsOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationPermissionList]
    def list_permissions(
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/permissions", auth: true, params: params)
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::AuthorizationPermission.new(item.to_json) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["before"] || metadata[:before]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_permissions(
          before: cursor,
          after: after,
          limit: limit,
          order: order,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next)
    end

    # Create a permission
    # @param slug [String] A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
    # @param name [String] A descriptive name for the Permission.
    # @param description [String, nil, nil] An optional description of the Permission.
    # @param resource_type_slug [String, nil] The slug of the resource type this permission is scoped to.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::Permission]
    def create_permission(
      slug:,
      name:,
      description: nil,
      resource_type_slug: nil,
      request_options: {}
    )
      body = {
        "slug" => slug,
        "name" => name,
        "description" => description,
        "resource_type_slug" => resource_type_slug
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/authorization/permissions", auth: true, body: body)
      )
      WorkOS::Permission.new(response.body)
    end

    # Get a permission
    # @param slug [String] A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationPermission]
    def get_permission(
      slug:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.get_request(path: "/authorization/permissions/#{slug}", auth: true)
      )
      WorkOS::AuthorizationPermission.new(response.body)
    end

    # Update a permission
    # @param slug [String] A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
    # @param name [String, nil] A descriptive name for the Permission.
    # @param description [String, nil, nil] An optional description of the Permission.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [WorkOS::AuthorizationPermission]
    def update_permission(
      slug:,
      name: nil,
      description: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "description" => description
      }.compact
      response = @client.execute_request(
        request: @client.patch_request(path: "/authorization/permissions/#{slug}", auth: true, body: body)
      )
      WorkOS::AuthorizationPermission.new(response.body)
    end

    # Delete a permission
    # @param slug [String] A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks.
    # @param request_options [Hash] Per-request overrides (headers, timeout, etc.).
    # @return [Object]
    def delete_permission(
      slug:,
      request_options: {}
    )
      @client.execute_request(
        request: @client.delete_request(path: "/authorization/permissions/#{slug}", auth: true)
      )
      nil
    end
  end
end
