# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class Client < BaseClient
    def api_keys
      @api_keys ||= WorkOS::ApiKeys.new(self)
    end

    def multi_factor_auth
      @multi_factor_auth ||= WorkOS::MultiFactorAuth.new(self)
    end

    def connect
      @connect ||= WorkOS::Connect.new(self)
    end

    def authorization
      @authorization ||= WorkOS::Authorization.new(self)
    end

    def sso
      @sso ||= WorkOS::SSO.new(self)
    end

    def pipes
      @pipes ||= WorkOS::Pipes.new(self)
    end

    def directory_sync
      @directory_sync ||= WorkOS::DirectorySync.new(self)
    end

    def events
      @events ||= WorkOS::Events.new(self)
    end

    def feature_flags
      @feature_flags ||= WorkOS::FeatureFlags.new(self)
    end

    def organization_domains
      @organization_domains ||= WorkOS::OrganizationDomains.new(self)
    end

    def organizations
      @organizations ||= WorkOS::Organizations.new(self)
    end

    def admin_portal
      @admin_portal ||= WorkOS::AdminPortal.new(self)
    end

    def radar
      @radar ||= WorkOS::Radar.new(self)
    end

    def user_management
      @user_management ||= WorkOS::UserManagement.new(self)
    end

    def webhooks
      @webhooks ||= WorkOS::Webhooks.new(self)
    end

    def widgets
      @widgets ||= WorkOS::Widgets.new(self)
    end

    def audit_logs
      @audit_logs ||= WorkOS::AuditLogs.new(self)
    end
  end
end
