# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module WorkOS
  class Connect
    def initialize(client)
      @client = client
    end

    # Complete external authentication
    # @param external_auth_id [String] Identifier provided when AuthKit redirected to your login page.
    # @param user [WorkOS::UserObject] The user to create or update in AuthKit.
    # @param user_consent_options [Array<WorkOS::UserConsentOption>, nil] Array of [User Consent Options](https://workos.com/docs/reference/workos-connect/standalone/user-consent-options) to store with the session.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::ExternalAuthCompleteResponse]
    def complete_oauth2(
      external_auth_id:,
      user:,
      user_consent_options: nil,
      request_options: {}
    )
      body = {
        'external_auth_id' => external_auth_id,
        'user' => user,
        'user_consent_options' => user_consent_options
      }.compact
      response = @client.request(
        method: :post,
        path: '/authkit/oauth2/complete',
        auth: true,
        body: body,
        request_options: request_options
      )
      result = WorkOS::ExternalAuthCompleteResponse.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # List Connect Applications
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::ApplicationsOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param organization_id [String, nil] Filter Connect Applications by organization ID.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Types::ListStruct<WorkOS::ConnectApplication>]
    def list_applications(
      before: nil,
      after: nil,
      limit: nil,
      order: 'desc',
      organization_id: nil,
      request_options: {}
    )
      params = {
        'before' => before,
        'after' => after,
        'limit' => limit,
        'order' => order,
        'organization_id' => organization_id
      }.compact
      response = @client.request(
        method: :get,
        path: '/connect/applications',
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = ->(cursor) {
        list_applications(
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          organization_id: organization_id,
          request_options: request_options
        )
      }
      WorkOS::Types::ListStruct.from_response(
        response,
        model: WorkOS::ConnectApplication,
        filters: { before: before, limit: limit, order: order, organization_id: organization_id },
        fetch_next: fetch_next
      )
    end

    # Create a Connect Application
    # @param name [String] The name of the application.
    # @param application_type [String] The type of application to create.
    # @param description [String, nil] A description for the application.
    # @param scopes [Array<String>, nil] The OAuth scopes granted to the application.
    # @param redirect_uris [Array<WorkOS::RedirectUriInput>, nil] Redirect URIs for the application.
    # @param uses_pkce [Boolean, nil] Whether the application uses PKCE (Proof Key for Code Exchange).
    # @param is_first_party [Boolean, nil] Whether this is a first-party application. Third-party applications require an organization_id.
    # @param organization_id [String, nil] The organization ID this application belongs to. Required when is_first_party is false.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::ConnectApplication]
    def create_application(
      name:,
      application_type:,
      description: nil,
      scopes: nil,
      redirect_uris: nil,
      uses_pkce: nil,
      is_first_party: nil,
      organization_id: nil,
      request_options: {}
    )
      body = {
        'name' => name,
        'application_type' => application_type,
        'description' => description,
        'scopes' => scopes,
        'redirect_uris' => redirect_uris,
        'uses_pkce' => uses_pkce,
        'is_first_party' => is_first_party,
        'organization_id' => organization_id
      }.compact
      response = @client.request(
        method: :post,
        path: '/connect/applications',
        auth: true,
        body: body,
        request_options: request_options
      )
      result = WorkOS::ConnectApplication.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Create oauth application.
    # @param name [String]
    # @param is_first_party [Boolean]
    # @param description [String, nil]
    # @param scopes [Array<String>, nil]
    # @param redirect_uris [Array<WorkOS::RedirectUriInput>, nil]
    # @param uses_pkce [Boolean, nil]
    # @param organization_id [String, nil]
    # @param request_options [Hash] Per-request overrides.
    # @return [WorkOS::ConnectApplication]
    def create_oauth_application(
      name:,
      is_first_party:,
      description: nil,
      scopes: nil,
      redirect_uris: nil,
      uses_pkce: nil,
      organization_id: nil,
      request_options: {}
    )
      body = {
        'application_type' => 'oauth',
        'name' => name,
        'is_first_party' => is_first_party,
        'description' => description,
        'scopes' => scopes,
        'redirect_uris' => redirect_uris,
        'uses_pkce' => uses_pkce,
        'organization_id' => organization_id
      }.compact
      response = @client.request(
        method: :post,
        path: '/connect/applications',
        auth: true,
        body: body,
        request_options: request_options
      )
      WorkOS::ConnectApplication.new(response.body)
    end

    # Create m2m application.
    # @param name [String]
    # @param organization_id [String]
    # @param description [String, nil]
    # @param scopes [Array<String>, nil]
    # @param request_options [Hash] Per-request overrides.
    # @return [WorkOS::ConnectApplication]
    def create_m2m_application(
      name:,
      organization_id:,
      description: nil,
      scopes: nil,
      request_options: {}
    )
      body = {
        'application_type' => 'm2m',
        'name' => name,
        'organization_id' => organization_id,
        'description' => description,
        'scopes' => scopes
      }.compact
      response = @client.request(
        method: :post,
        path: '/connect/applications',
        auth: true,
        body: body,
        request_options: request_options
      )
      WorkOS::ConnectApplication.new(response.body)
    end

    # Get a Connect Application
    # @param id [String] The application ID or client ID of the Connect Application.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::ConnectApplication]
    def get_application(
      id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/connect/applications/#{WorkOS::Util.encode_path(id)}",
        auth: true,
        request_options: request_options
      )
      result = WorkOS::ConnectApplication.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Update a Connect Application
    # @param id [String] The application ID or client ID of the Connect Application.
    # @param name [String, nil] The name of the application.
    # @param description [String, nil] A description for the application.
    # @param scopes [Array<String>, nil] The OAuth scopes granted to the application.
    # @param redirect_uris [Array<WorkOS::RedirectUriInput>, nil] Updated redirect URIs for the application. OAuth applications only.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::ConnectApplication]
    def update_application(
      id:,
      name: nil,
      description: nil,
      scopes: nil,
      redirect_uris: nil,
      request_options: {}
    )
      body = {
        'name' => name,
        'description' => description,
        'scopes' => scopes,
        'redirect_uris' => redirect_uris
      }.compact
      response = @client.request(
        method: :put,
        path: "/connect/applications/#{WorkOS::Util.encode_path(id)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = WorkOS::ConnectApplication.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Delete a Connect Application
    # @param id [String] The application ID or client ID of the Connect Application.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [void]
    def delete_application(
      id:,
      request_options: {}
    )
      response = @client.request(
        method: :delete,
        path: "/connect/applications/#{WorkOS::Util.encode_path(id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end

    # List Client Secrets for a Connect Application
    # @param id [String] The application ID or client ID of the Connect Application.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [Array<WorkOS::ApplicationCredentialsListItem>]
    def list_application_client_secrets(
      id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/connect/applications/#{WorkOS::Util.encode_path(id)}/client_secrets",
        auth: true,
        request_options: request_options
      )
      parsed = JSON.parse(response.body)
      (parsed || []).map { |item| WorkOS::ApplicationCredentialsListItem.new(item) }
    end

    # Create a new client secret for a Connect Application
    # @param id [String] The application ID or client ID of the Connect Application.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::NewConnectApplicationSecret]
    def create_application_client_secret(
      id:,
      request_options: {}
    )
      response = @client.request(
        method: :post,
        path: "/connect/applications/#{WorkOS::Util.encode_path(id)}/client_secrets",
        auth: true,
        request_options: request_options
      )
      result = WorkOS::NewConnectApplicationSecret.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Delete a Client Secret
    # @param id [String] The unique ID of the client secret.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [void]
    def delete_client_secret(
      id:,
      request_options: {}
    )
      response = @client.request(
        method: :delete,
        path: "/connect/client_secrets/#{WorkOS::Util.encode_path(id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end
  end
end
