# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class CreateUser
    include HashProvider

    attr_accessor \
      :email,
      :password,
      :password_hash,
      :password_hash_type,
      :first_name,
      :last_name,
      :email_verified,
      :metadata,
      :external_id

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @email = hash[:email]
      @password = hash[:password]
      @password_hash = hash[:password_hash]
      @password_hash_type = hash[:password_hash_type]
      @first_name = hash[:first_name]
      @last_name = hash[:last_name]
      @email_verified = hash[:email_verified]
      @metadata = hash[:metadata] || {}
      @external_id = hash[:external_id]
    end

    def to_json(*)
      {
        email: email,
        password: password,
        password_hash: password_hash,
        password_hash_type: password_hash_type,
        first_name: first_name,
        last_name: last_name,
        email_verified: email_verified,
        metadata: metadata,
        external_id: external_id
      }
    end
  end
end
