# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DataIntegrationsListResponseDataConnectedAccount
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :user_id,
      :organization_id,
      :scopes,
      :state,
      :created_at,
      :updated_at,
      :userland_user_id

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @user_id = hash[:user_id]
      @organization_id = hash[:organization_id]
      @scopes = hash[:scopes] || []
      @state = hash[:state]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @userland_user_id = hash[:userlandUserId]
    end

    def to_json(*)
      {
        object: object,
        id: id,
        user_id: user_id,
        organization_id: organization_id,
        scopes: scopes,
        state: state,
        created_at: created_at,
        updated_at: updated_at,
        userlandUserId: userland_user_id
      }
    end
  end
end
