# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DsyncDeletedData
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :organization_id,
      :type,
      :state,
      :name,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @organization_id = hash[:organization_id]
      @type = hash[:type]
      @state = hash[:state]
      @name = hash[:name]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end

    def to_json(*)
      {
        object: object,
        id: id,
        organization_id: organization_id,
        type: type,
        state: state,
        name: name,
        created_at: created_at,
        updated_at: updated_at
      }
    end
  end
end
