# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class EventContextGoogleAnalyticsSession
    include HashProvider

    attr_accessor \
      :container_id,
      :session_id,
      :session_number

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @container_id = hash[:containerId]
      @session_id = hash[:sessionId]
      @session_number = hash[:sessionNumber]
    end

    def to_json(*)
      {
        containerId: container_id,
        sessionId: session_id,
        sessionNumber: session_number
      }
    end
  end
end
