# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class Events
    def initialize(client)
      @client = client
    end

    # List events
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::EventsOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param events [Array<String>, nil] Filter events by one or more event types (e.g. `dsync.user.created`).
    # @param range_start [String, nil] ISO-8601 date string to filter events created after this date.
    # @param range_end [String, nil] ISO-8601 date string to filter events created before this date.
    # @param organization_id [String, nil] Filter events by the [Organization](https://workos.com/docs/reference/organization) that the event is associated with.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::Types::ListStruct]
    def list_events(
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      events: nil,
      range_start: nil,
      range_end: nil,
      organization_id: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "events" => events,
        "range_start" => range_start,
        "range_end" => range_end,
        "organization_id" => organization_id
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/events", auth: true, params: params, request_options: request_options),
        request_options: request_options
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::EventSchema.new(item) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["after"] || metadata[:after]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_events(
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          events: events,
          range_start: range_start,
          range_end: range_end,
          organization_id: organization_id,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next, filters: {before: before, limit: limit, order: order, events: events, range_start: range_start, range_end: range_end, organization_id: organization_id})
    end
  end
end
