# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module WorkOS
  class FeatureFlags
    def initialize(client)
      @client = client
    end

    # List feature flags
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::FeatureFlagsOrder, nil] Order the results by the creation time.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Types::ListStruct<WorkOS::Flag>]
    def list_feature_flags(
      before: nil,
      after: nil,
      limit: nil,
      order: 'desc',
      request_options: {}
    )
      params = {
        'before' => before,
        'after' => after,
        'limit' => limit,
        'order' => order
      }.compact
      response = @client.request(
        method: :get,
        path: '/feature-flags',
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = ->(cursor) {
        list_feature_flags(
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          request_options: request_options
        )
      }
      WorkOS::Types::ListStruct.from_response(
        response,
        model: WorkOS::Flag,
        filters: { before: before, limit: limit, order: order },
        fetch_next: fetch_next
      )
    end

    # Get a feature flag
    # @param slug [String] A unique key to reference the Feature Flag.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Flag]
    def get_feature_flag(
      slug:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/feature-flags/#{WorkOS::Util.encode_path(slug)}",
        auth: true,
        request_options: request_options
      )
      result = WorkOS::Flag.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Disable a feature flag
    # @param slug [String] A unique key to reference the Feature Flag.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::FeatureFlag]
    def disable_feature_flag(
      slug:,
      request_options: {}
    )
      response = @client.request(
        method: :put,
        path: "/feature-flags/#{WorkOS::Util.encode_path(slug)}/disable",
        auth: true,
        request_options: request_options
      )
      result = WorkOS::FeatureFlag.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Enable a feature flag
    # @param slug [String] A unique key to reference the Feature Flag.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::FeatureFlag]
    def enable_feature_flag(
      slug:,
      request_options: {}
    )
      response = @client.request(
        method: :put,
        path: "/feature-flags/#{WorkOS::Util.encode_path(slug)}/enable",
        auth: true,
        request_options: request_options
      )
      result = WorkOS::FeatureFlag.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Add a feature flag target
    # @param resource_id [String] The resource ID in format "user_<id>" or "org_<id>".
    # @param slug [String] The unique slug identifier of the feature flag.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [void]
    def add_flag_target(
      resource_id:,
      slug:,
      request_options: {}
    )
      response = @client.request(
        method: :post,
        path: "/feature-flags/#{WorkOS::Util.encode_path(slug)}/targets/#{WorkOS::Util.encode_path(resource_id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end

    # Remove a feature flag target
    # @param resource_id [String] The resource ID in format "user_<id>" or "org_<id>".
    # @param slug [String] The unique slug identifier of the feature flag.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [void]
    def remove_flag_target(
      resource_id:,
      slug:,
      request_options: {}
    )
      response = @client.request(
        method: :delete,
        path: "/feature-flags/#{WorkOS::Util.encode_path(slug)}/targets/#{WorkOS::Util.encode_path(resource_id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end

    # List enabled feature flags for an organization
    # @param organization_id [String] Unique identifier of the Organization.
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::OrganizationsFeatureFlagsOrder, nil] Order the results by the creation time.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Types::ListStruct<WorkOS::Flag>]
    def list_organization_feature_flags(
      organization_id:,
      before: nil,
      after: nil,
      limit: nil,
      order: 'desc',
      request_options: {}
    )
      params = {
        'before' => before,
        'after' => after,
        'limit' => limit,
        'order' => order
      }.compact
      response = @client.request(
        method: :get,
        path: "/organizations/#{WorkOS::Util.encode_path(organization_id)}/feature-flags",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = ->(cursor) {
        list_organization_feature_flags(
          organization_id: organization_id,
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          request_options: request_options
        )
      }
      WorkOS::Types::ListStruct.from_response(
        response,
        model: WorkOS::Flag,
        filters: { organization_id: organization_id, before: before, limit: limit, order: order },
        fetch_next: fetch_next
      )
    end

    # List enabled feature flags for a user
    # @param user_id [String] The ID of the user.
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::UserManagementUsersFeatureFlagsOrder, nil] Order the results by the creation time.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Types::ListStruct<WorkOS::Flag>]
    def list_user_feature_flags(
      user_id:,
      before: nil,
      after: nil,
      limit: nil,
      order: 'desc',
      request_options: {}
    )
      params = {
        'before' => before,
        'after' => after,
        'limit' => limit,
        'order' => order
      }.compact
      response = @client.request(
        method: :get,
        path: "/user_management/users/#{WorkOS::Util.encode_path(user_id)}/feature-flags",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = ->(cursor) {
        list_user_feature_flags(
          user_id: user_id,
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          request_options: request_options
        )
      }
      WorkOS::Types::ListStruct.from_response(
        response,
        model: WorkOS::Flag,
        filters: { user_id: user_id, before: before, limit: limit, order: order },
        fetch_next: fetch_next
      )
    end
  end
end
