# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "cgi"
require "json"

module WorkOS
  class MultiFactorAuth
    def initialize(client)
      @client = client
    end

    # Verify Challenge
    # @param id [String] The unique ID of the Authentication Challenge.
    # @param code [String] The one-time code to verify.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::AuthenticationChallengeVerifyResponse]
    def verify_challenge(
      id:,
      code:,
      request_options: {}
    )
      body = {
        "code" => code
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/auth/challenges/#{CGI.escape(id.to_s)}/verify", auth: true, body: body, request_options: request_options),
        request_options: request_options
      )
      WorkOS::AuthenticationChallengeVerifyResponse.new(response.body)
    end

    # Enroll Factor
    # @param type [WorkOS::Types::AuthenticationFactorsCreateRequestType] The type of factor to enroll.
    # @param phone_number [String, nil] Required when type is 'sms'.
    # @param totp_issuer [String, nil] Required when type is 'totp'.
    # @param totp_user [String, nil] Required when type is 'totp'.
    # @param user_id [String, nil] The ID of the user to associate the factor with.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::AuthenticationFactorEnrolled]
    def enroll_factor(
      type:,
      phone_number: nil,
      totp_issuer: nil,
      totp_user: nil,
      user_id: nil,
      request_options: {}
    )
      body = {
        "type" => type,
        "phone_number" => phone_number,
        "totp_issuer" => totp_issuer,
        "totp_user" => totp_user,
        "user_id" => user_id
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/auth/factors/enroll", auth: true, body: body, request_options: request_options),
        request_options: request_options
      )
      WorkOS::AuthenticationFactorEnrolled.new(response.body)
    end

    # Get Factor
    # @param id [String] The unique ID of the Factor.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::AuthenticationFactor]
    def get_factor(
      id:,
      request_options: {}
    )
      response = @client.execute_request(
        request: @client.get_request(path: "/auth/factors/#{CGI.escape(id.to_s)}", auth: true, request_options: request_options),
        request_options: request_options
      )
      WorkOS::AuthenticationFactor.new(response.body)
    end

    # Delete Factor
    # @param id [String] The unique ID of the Factor.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [void]
    def delete_factor(
      id:,
      request_options: {}
    )
      @client.execute_request(
        request: @client.delete_request(path: "/auth/factors/#{CGI.escape(id.to_s)}", auth: true, request_options: request_options),
        request_options: request_options
      )
      nil
    end

    # Challenge Factor
    # @param id [String] The unique ID of the Authentication Factor to be challenged.
    # @param sms_template [String, nil] A custom template for the SMS message. Use the {{code}} placeholder to include the verification code.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::AuthenticationChallenge]
    def challenge_factor(
      id:,
      sms_template: nil,
      request_options: {}
    )
      body = {
        "sms_template" => sms_template
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/auth/factors/#{CGI.escape(id.to_s)}/challenge", auth: true, body: body, request_options: request_options),
        request_options: request_options
      )
      WorkOS::AuthenticationChallenge.new(response.body)
    end

    # List authentication factors
    # @param userland_user_id [String] The ID of the [user](https://workos.com/docs/reference/authkit/user).
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::UserManagementMultiFactorAuthenticationOrder, nil] Order the results by the creation time.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::Types::ListStruct]
    def list_user_auth_factors(
      userland_user_id:,
      before: nil,
      after: nil,
      limit: nil,
      order: "desc",
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order
      }.compact
      response = @client.execute_request(
        request: @client.get_request(path: "/user_management/users/#{CGI.escape(userland_user_id.to_s)}/auth_factors", auth: true, params: params, request_options: request_options),
        request_options: request_options
      )
      parsed = JSON.parse(response.body)
      items = (parsed["data"] || []).map { |item| WorkOS::AuthenticationFactor.new(item) }
      fetch_next = lambda do |metadata|
        cursor = metadata.is_a?(Hash) ? (metadata["after"] || metadata[:after]) : nil
        return nil if cursor.nil? || cursor.to_s.empty?
        list_user_auth_factors(
          userland_user_id: userland_user_id,
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          request_options: request_options
        )
      end
      WorkOS::Types::ListStruct.new(data: items, list_metadata: parsed["list_metadata"], fetch_next: fetch_next, filters: {userland_user_id: userland_user_id, before: before, limit: limit, order: order})
    end

    # Enroll an authentication factor
    # @param userland_user_id [String] The ID of the [user](https://workos.com/docs/reference/authkit/user).
    # @param type [String] The type of the factor to enroll.
    # @param totp_issuer [String, nil] Your application or company name displayed in the user's authenticator app.
    # @param totp_user [String, nil] The user's account name displayed in their authenticator app.
    # @param totp_secret [String, nil] The Base32-encoded shared secret for TOTP factors. This can be provided when creating the auth factor, otherwise it will be generated. The algorithm used to derive TOTP codes is SHA-1, the code length is 6 digits, and the timestep is 30 seconds – the secret must be compatible with these parameters.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::UserAuthenticationFactorEnrollResponse]
    def create_user_auth_factor(
      userland_user_id:,
      type:,
      totp_issuer: nil,
      totp_user: nil,
      totp_secret: nil,
      request_options: {}
    )
      body = {
        "type" => type,
        "totp_issuer" => totp_issuer,
        "totp_user" => totp_user,
        "totp_secret" => totp_secret
      }.compact
      response = @client.execute_request(
        request: @client.post_request(path: "/user_management/users/#{CGI.escape(userland_user_id.to_s)}/auth_factors", auth: true, body: body, request_options: request_options),
        request_options: request_options
      )
      WorkOS::UserAuthenticationFactorEnrollResponse.new(response.body)
    end
  end
end
