# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  # Identifies the parent resource (by external id variant).
  #
  # @!attribute [r] parent_resource_type_slug
  #   @return [String]
  # @!attribute [r] parent_resource_external_id
  #   @return [String]
  ParentResourceByExternalId = Data.define(:parent_resource_type_slug, :parent_resource_external_id)
end
