# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  # Identifies the password (hashed variant).
  #
  # @!attribute [r] password_hash
  #   @return [String]
  # @!attribute [r] password_hash_type
  #   @return [WorkOS::Types::CreateUserPasswordHashType]
  PasswordHashed = Data.define(:password_hash, :password_hash_type)
end
