# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class PortalLinkResponse
    include HashProvider

    attr_accessor :link

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @link = hash[:link]
    end

    def to_json(*)
      {
        link: link
      }
    end
  end
end
