# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class RadarListEntryAlreadyPresentResponse
    include HashProvider

    attr_accessor :message

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @message = hash[:message]
    end

    def to_json(*)
      {
        message: message
      }
    end
  end
end
