# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class RedirectUriInput
    include HashProvider

    attr_accessor \
      :uri,
      :default

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @uri = hash[:uri]
      @default = hash[:default]
    end

    def to_json(*)
      {
        uri: uri,
        default: default
      }
    end
  end
end
