# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  # Identifies the role (single variant).
  #
  # @!attribute [r] role_slug
  #   @return [String]
  RoleSingle = Data.define(:role_slug)
end
