# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class SessionCreatedData
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :impersonator,
      :ip_address,
      :organization_id,
      :user_agent,
      :user_id,
      :auth_method,
      :status,
      :expires_at,
      :ended_at,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @impersonator = hash[:impersonator] ? WorkOS::SessionCreatedDataImpersonator.new(hash[:impersonator].to_json) : nil
      @ip_address = hash[:ip_address]
      @organization_id = hash[:organization_id]
      @user_agent = hash[:user_agent]
      @user_id = hash[:user_id]
      @auth_method = hash[:auth_method]
      @status = hash[:status]
      @expires_at = hash[:expires_at]
      @ended_at = hash[:ended_at]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end

    def to_json(*)
      {
        object: object,
        id: id,
        impersonator: impersonator&.to_json,
        ip_address: ip_address,
        organization_id: organization_id,
        user_agent: user_agent,
        user_id: user_id,
        auth_method: auth_method,
        status: status,
        expires_at: expires_at,
        ended_at: ended_at,
        created_at: created_at,
        updated_at: updated_at
      }
    end
  end
end
