# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"
require "uri"

module WorkOS
  class SSO
    def initialize(client)
      @client = client
    end

    # List Connections
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::PaginationOrder, nil] Order the results by the creation time.
    # @param connection_type [WorkOS::Types::ConnectionsConnectionType, nil] Filter Connections by their type.
    # @param domain [String, nil] Filter Connections by their associated domain.
    # @param organization_id [String, nil] Filter Connections by their associated organization.
    # @param search [String, nil] Searchable text to match against Connection names.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Types::ListStruct<WorkOS::Connection>]
    def list_connections(
      before: nil,
      after: nil,
      limit: 10,
      order: "desc",
      connection_type: nil,
      domain: nil,
      organization_id: nil,
      search: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "connection_type" => connection_type,
        "domain" => domain,
        "organization_id" => organization_id,
        "search" => search
      }.compact
      response = @client.request(
        method: :get,
        path: "/connections",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = ->(cursor) {
        list_connections(
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          connection_type: connection_type,
          domain: domain,
          organization_id: organization_id,
          search: search,
          request_options: request_options
        )
      }
      WorkOS::Types::ListStruct.from_response(
        response,
        model: WorkOS::Connection,
        filters: {before: before, limit: limit, order: order, connection_type: connection_type, domain: domain, organization_id: organization_id, search: search},
        fetch_next: fetch_next
      )
    end

    # Get a Connection
    # @param id [String] Unique identifier for the Connection.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Connection]
    def get_connection(
      id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/connections/#{WorkOS::Util.encode_path(id)}",
        auth: true,
        request_options: request_options
      )
      result = WorkOS::Connection.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Delete a Connection
    # @param id [String] Unique identifier for the Connection.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [void]
    def delete_connection(
      id:,
      request_options: {}
    )
      @client.request(
        method: :delete,
        path: "/connections/#{WorkOS::Util.encode_path(id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end

    # Initiate SSO
    # Builds the URL client-side; no HTTP request is made.
    # @param provider_scopes [Array<String>, nil] Additional scopes to request from the identity provider. Applicable when using OAuth or OpenID Connect connections.
    # @param provider_query_params [Hash{String => String}, nil] Key/value pairs of query parameters to pass to the OAuth provider. Only applicable when using OAuth connections.
    # @param client_id [String, nil] The unique identifier of the WorkOS environment client. Defaults to the client's configured client_id.
    # @param domain [String, nil] Deprecated. Use `connection` or `organization` instead. Used to initiate SSO for a connection by domain. The domain must be associated with a connection in your WorkOS environment.
    # @param provider [WorkOS::Types::SSOProvider, nil] Used to initiate OAuth authentication with various providers.
    # @param redirect_uri [String] Where to redirect the user after they complete the authentication process. You must use one of the redirect URIs configured via the [Redirects](https://dashboard.workos.com/redirects) page on the dashboard.
    # @param state [String, nil] An optional parameter that can be used to encode arbitrary information to help restore application state between redirects. If included, the redirect URI received from WorkOS will contain the exact `state` that was passed.
    # @param connection [String, nil] Used to initiate SSO for a connection. The value should be a WorkOS connection ID. You can persist the WorkOS connection ID with application user or team identifiers. WorkOS will use the connection indicated by the connection parameter to direct the user to the corresponding IdP for authentication.
    # @param organization [String, nil] Used to initiate SSO for an organization. The value should be a WorkOS organization ID. You can persist the WorkOS organization ID with application user or team identifiers. WorkOS will use the organization ID to determine the appropriate connection and the IdP to direct the user to for authentication.
    # @param domain_hint [String, nil] Can be used to pre-fill the domain field when initiating authentication with Microsoft OAuth or with a Google SAML connection type.
    # @param login_hint [String, nil] Can be used to pre-fill the username/email address field of the IdP sign-in page for the user, if you know their username ahead of time. Currently supported for OAuth, OpenID Connect, Okta, Entra ID, and custom SAML connections.
    # @param nonce [String, nil] A random string generated by the client that is used to mitigate replay attacks.
    # @param prompt [String, nil] If set to `login`, forces re-authentication at the identity provider. For supported SAML providers this sets `ForceAuthn="true"` in the SAML request; providers that don't support it are unaffected.
    # @return [String]
    def get_authorization_url(
      redirect_uri:,
      provider_scopes: nil,
      provider_query_params: nil,
      client_id: nil,
      domain: nil,
      provider: nil,
      state: nil,
      connection: nil,
      organization: nil,
      domain_hint: nil,
      login_hint: nil,
      nonce: nil,
      prompt: nil
    )
      params = {
        "provider_scopes" => provider_scopes,
        "provider_query_params" => provider_query_params,
        "client_id" => client_id,
        "domain" => domain,
        "provider" => provider,
        "redirect_uri" => redirect_uri,
        "state" => state,
        "connection" => connection,
        "organization" => organization,
        "domain_hint" => domain_hint,
        "login_hint" => login_hint,
        "nonce" => nonce,
        "prompt" => prompt
      }.compact
      params["provider_scopes"] = provider_scopes.join(",") unless provider_scopes.nil?
      params["provider_query_params"] = JSON.generate(provider_query_params) unless provider_query_params.nil?
      params["response_type"] = "code"
      params["client_id"] = @client.client_id if !params.key?("client_id") && !@client.client_id.nil?
      uri = URI.join(@client.base_url, "/sso/authorize")
      uri.query = URI.encode_www_form(params) unless params.empty?
      uri.to_s
    end

    # Logout Redirect
    # Builds the URL client-side; no HTTP request is made.
    # @param token [String] The logout token returned from the [Logout Authorize](https://workos.com/docs/reference/sso/logout/authorize) endpoint.
    # @return [String]
    def get_logout_url(token:)
      params = {
        "token" => token
      }
      uri = URI.join(@client.base_url, "/sso/logout")
      uri.query = URI.encode_www_form(params) unless params.empty?
      uri.to_s
    end

    # Logout Authorize
    # @param profile_id [String] The unique ID of the profile to log out.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::SSOLogoutAuthorizeResponse]
    def authorize_logout(
      profile_id:,
      request_options: {}
    )
      body = {
        "profile_id" => profile_id
      }
      response = @client.request(
        method: :post,
        path: "/sso/logout/authorize",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = WorkOS::SSOLogoutAuthorizeResponse.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Get a User Profile
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::Profile]
    def get_profile(request_options: {})
      response = @client.request(
        method: :get,
        path: "/sso/profile",
        auth: true,
        request_options: request_options
      )
      result = WorkOS::Profile.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # Get a Profile and Token
    # @param code [String] The authorization code received from the authorization callback.
    # @param request_options [Hash] (see WorkOS::Types::RequestOptions)
    # @return [WorkOS::SSOTokenResponse]
    def get_profile_and_token(
      code:,
      request_options: {}
    )
      body = {
        "grant_type" => "authorization_code",
        "client_id" => request_options[:client_id] || @client.client_id,
        "client_secret" => request_options[:api_key] || @client.api_key,
        "code" => code
      }
      response = @client.request(
        method: :post,
        path: "/sso/token",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = WorkOS::SSOTokenResponse.new(response.body)
      result.last_response = WorkOS::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
      result
    end

    # @oagen-ignore-start — non-spec helpers (hand-maintained)
    # H14 (sso_authorization_url) is provided by the generated
    # `get_authorization_url` url-builder method, which accepts an optional
    # per-call `client_id` override falling back to the client's configured
    # value; no hand-maintained override is needed here.

    # H15 — SSO authorization URL with auto-generated PKCE pair + state.
    # Returns [url, code_verifier, state].
    def get_authorization_url_with_pkce(redirect_uri:, client_id: nil, **opts)
      pair = WorkOS::PKCE.generate_pair
      state = opts.delete(:state) || WorkOS::PKCE.generate_code_verifier
      url = get_authorization_url(
        redirect_uri: redirect_uri,
        client_id: client_id,
        state: state,
        **opts
      )
      url = append_query(url, {"code_challenge" => pair[:code_challenge], "code_challenge_method" => "S256"})
      [url, pair[:code_verifier], state]
    end

    # H16 — Exchange an SSO authorization code for a profile/token, with PKCE
    # support for public clients (no client_secret).
    def get_profile_and_token_with_pkce(code:, code_verifier:, client_id: nil, request_options: {})
      cid = client_id || @client.client_id
      raise ArgumentError, "client_id is required" if cid.nil? || cid.empty?
      body = {
        "grant_type" => "authorization_code",
        "client_id" => cid,
        "code" => code,
        "code_verifier" => code_verifier
      }
      response = @client.request(method: :post, path: "/sso/token", auth: false, body: body, request_options: request_options)
      WorkOS::SSOTokenResponse.new(response.body)
    end

    # H17 — Build the SSO logout redirect URL (no HTTP call).
    def build_logout_url(token:)
      build_url("/sso/logout", {"token" => token})
    end

    private

    def build_url(path, params)
      base = @client.base_url
      uri = URI.join(base, path)
      uri.query = URI.encode_www_form(params)
      uri.to_s
    end

    def append_query(url, params)
      uri = URI(url)
      existing = URI.decode_www_form(uri.query || "")
      merged = existing + params.to_a
      uri.query = URI.encode_www_form(merged)
      uri.to_s
    end
    # @oagen-ignore-end
  end
end
