# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class Webhooks
    def initialize(client)
      @client = client
    end

    # List Webhook Endpoints
    # @param before [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
    # @param after [String, nil] An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
    # @param limit [Integer, nil] Upper limit on the number of objects to return, between `1` and `100`.
    # @param order [WorkOS::Types::WebhooksOrder, nil] Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records). Defaults to descending.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::Types::ListStruct]
    def list_webhook_endpoints(
      before: nil,
      after: nil,
      limit: nil,
      order: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order
      }.compact
      response = @client.request(method: :get, path: "/webhook_endpoints", auth: true, params: params, request_options: request_options)
      WorkOS::Types::ListStruct.from_response(
        response, model: WorkOS::WebhookEndpoint, filters: {before: before, limit: limit, order: order},
        fetch_next: lambda do |cursor|
          list_webhook_endpoints(
            before: before,
            after: cursor,
            limit: limit,
            order: order,
            request_options: request_options
          )
        end,
        fetch_previous: lambda do |cursor|
          list_webhook_endpoints(
            before: cursor,
            after: nil,
            limit: limit,
            order: order,
            request_options: request_options
          )
        end
      )
    end

    # Create a Webhook Endpoint
    # @param endpoint_url [String] The HTTPS URL where webhooks will be sent.
    # @param events [Array<WorkOS::Types::CreateWebhookEndpointEvents>] The events that the Webhook Endpoint is subscribed to.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::WebhookEndpoint]
    def create_webhook_endpoint(
      endpoint_url:,
      events:,
      request_options: {}
    )
      body = {
        "endpoint_url" => endpoint_url,
        "events" => events
      }.compact
      response = @client.request(method: :post, path: "/webhook_endpoints", auth: true, body: body, request_options: request_options)
      WorkOS::WebhookEndpoint.new(response.body)
    end

    # Update a Webhook Endpoint
    # @param id [String] Unique identifier of the Webhook Endpoint.
    # @param endpoint_url [String, nil] The HTTPS URL where webhooks will be sent.
    # @param status [WorkOS::Types::UpdateWebhookEndpointStatus, nil] Whether the Webhook Endpoint is enabled or disabled.
    # @param events [Array<WorkOS::Types::UpdateWebhookEndpointEvents>, nil] The events that the Webhook Endpoint is subscribed to.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [WorkOS::WebhookEndpoint]
    def update_webhook_endpoint(
      id:,
      endpoint_url: nil,
      status: nil,
      events: nil,
      request_options: {}
    )
      body = {
        "endpoint_url" => endpoint_url,
        "status" => status,
        "events" => events
      }.compact
      response = @client.request(method: :patch, path: "/webhook_endpoints/#{WorkOS::Util.encode_path(id)}", auth: true, body: body, request_options: request_options)
      WorkOS::WebhookEndpoint.new(response.body)
    end

    # Delete a Webhook Endpoint
    # @param id [String] Unique identifier of the Webhook Endpoint.
    # @param request_options [Hash] Per-request overrides: :api_key, :timeout, :base_url, :max_retries, :idempotency_key, :extra_headers.
    # @return [void]
    def delete_webhook_endpoint(
      id:,
      request_options: {}
    )
      @client.request(method: :delete, path: "/webhook_endpoints/#{WorkOS::Util.encode_path(id)}", auth: true, request_options: request_options)
      nil
    end

    # @oagen-ignore-start — non-spec helpers (hand-maintained)
    require "openssl"

    DEFAULT_TOLERANCE_SECONDS = 180

    # Verify a webhook signature and return a typed event struct.
    #
    # @param payload [String] Raw webhook request body.
    # @param sig_header [String] Value of the WorkOS-Signature header.
    # @param secret [String] Webhook endpoint secret.
    # @param tolerance [Integer] Maximum event age in seconds.
    # @return [WorkOS::WebhookEvent] Typed event with .event, .data, .id, .created_at.
    # @raise [WorkOS::SignatureVerificationError] if verification fails.
    def construct_event(payload:, sig_header:, secret:, tolerance: DEFAULT_TOLERANCE_SECONDS)
      raw = verify_event(payload: payload, sig_header: sig_header, secret: secret, tolerance: tolerance)
      WebhookEvent.new(raw)
    end

    # Verify a webhook signature and return the deserialized event payload.
    #
    # @param payload [String] Raw webhook request body.
    # @param sig_header [String] Value of the WorkOS-Signature header
    #   (format: "t=<ms_timestamp>, v1=<hex_sig>").
    # @param secret [String] Webhook endpoint secret from the dashboard.
    # @param tolerance [Integer] Maximum age of the event in seconds.
    # @return [Hash] Parsed JSON payload.
    # @raise [WorkOS::SignatureVerificationError] if signature or timestamp invalid.
    def verify_event(payload:, sig_header:, secret:, tolerance: DEFAULT_TOLERANCE_SECONDS)
      verify_header(payload: payload, sig_header: sig_header, secret: secret, tolerance: tolerance)
      JSON.parse(payload)
    end

    # Verify the signature without deserializing. Raises on failure.
    def verify_header(payload:, sig_header:, secret:, tolerance: DEFAULT_TOLERANCE_SECONDS)
      timestamp_ms, signature_hash = parse_signature_header(sig_header)
      max_age = tolerance.to_i
      issued_at = timestamp_ms.to_i / 1000.0
      if (Time.now.to_f - issued_at) > max_age
        raise WorkOS::SignatureVerificationError.new(
          message: "Timestamp outside the tolerance zone",
          http_status: nil
        )
      end

      expected = compute_signature(payload: payload, timestamp: timestamp_ms, secret: secret)
      unless secure_compare(signature_hash, expected)
        raise WorkOS::SignatureVerificationError.new(
          message: "Signature hash does not match the expected signature hash for payload",
          http_status: nil
        )
      end
      true
    end

    # Compute the HMAC-SHA256 hex signature for a (timestamp, payload) pair.
    # Exposed publicly so users can build their own verification flow.
    def compute_signature(payload:, timestamp:, secret:)
      WorkOS::Util::Signature.compute(payload: payload, timestamp: timestamp, secret: secret)
    end

    # Parse a "t=<ms>, v1=<sig>" header into [timestamp, signature].
    # Exposed publicly for advanced use.
    def parse_signature_header(sig_header)
      WorkOS::Util::Signature.parse_header(sig_header)
    rescue ArgumentError => e
      raise WorkOS::SignatureVerificationError.new(message: e.message, http_status: nil)
    end

    private

    def secure_compare(a, b)
      WorkOS::Util::Signature.secure_compare(a, b)
    end
    # @oagen-ignore-end
  end
end
