# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class AuthenticationSSOFailedDataSSO
    include HashProvider

    attr_accessor \
      :organization_id,
      :connection_id,
      :session_id

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @organization_id = hash[:organization_id]
      @connection_id = hash[:connection_id]
      @session_id = hash[:session_id]
    end

    def to_h
      {
        organization_id: organization_id,
        connection_id: connection_id,
        session_id: session_id
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

    def inspect
      "#<#{self.class}>"
    end
  end
end
