# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class AuthenticationSSOFailedData
    include HashProvider

    attr_accessor \
      :type,
      :status,
      :ip_address,
      :user_agent,
      :user_id,
      :email,
      :sso,
      :error

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @type = hash[:type]
      @status = hash[:status]
      @ip_address = hash[:ip_address]
      @user_agent = hash[:user_agent]
      @user_id = hash[:user_id]
      @email = hash[:email]
      @sso = hash[:sso] ? WorkOS::AuthenticationSSOFailedDataSSO.new(hash[:sso].to_json) : nil
      @error = hash[:error] ? WorkOS::AuthenticationSSOFailedDataError.new(hash[:error].to_json) : nil
    end

    def to_json(*)
      {
        type: type,
        status: status,
        ip_address: ip_address,
        user_agent: user_agent,
        user_id: user_id,
        email: email,
        sso: sso&.to_json,
        error: error&.to_json
      }
    end
  end
end
