# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class AuthorizedConnectApplicationListData
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :granted_scopes,
      :oauth_resource,
      :application

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @granted_scopes = hash[:granted_scopes] || []
      @oauth_resource = hash[:oauth_resource]
      @application = hash[:application] ? WorkOS::ConnectApplication.new(hash[:application]) : nil
    end

    def to_h
      {
        object: object,
        id: id,
        granted_scopes: granted_scopes,
        oauth_resource: oauth_resource,
        application: application&.to_h
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end
  end
end
