# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AuthenticationSSOTimedOutData < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      type: :type,
      status: :status,
      ip_address: :ip_address,
      user_agent: :user_agent,
      user_id: :user_id,
      email: :email,
      sso: :sso,
      error: :error
    }.freeze

    attr_accessor \
      :type,
      :status,
      :ip_address,
      :user_agent,
      :user_id,
      :email,
      :sso,
      :error

    def initialize(json)
      hash = self.class.normalize(json)
      @type = hash[:type]
      @status = hash[:status]
      @ip_address = hash[:ip_address]
      @user_agent = hash[:user_agent]
      @user_id = hash[:user_id]
      @email = hash[:email]
      @sso = hash[:sso] ? WorkOS::AuthenticationSSOTimedOutDataSSO.new(hash[:sso]) : nil
      @error = hash[:error] ? WorkOS::AuthenticationSSOTimedOutDataError.new(hash[:error]) : nil
    end
  end
end
