# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class CreateWaitlistEntry < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      email: :email,
      additional_fields: :additional_fields,
      send_confirmation_email: :send_confirmation_email
    }.freeze

    attr_accessor \
      :email,
      :additional_fields,
      :send_confirmation_email

    def initialize(json)
      hash = self.class.normalize(json)
      @email = hash[:email]
      @additional_fields = hash[:additional_fields] || {}
      @send_confirmation_email = hash[:send_confirmation_email]
    end
  end
end
