# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class CreateMagicCodeAndReturn
    include HashProvider

    HASH_ATTRS = {
      email: :email,
      invitation_token: :invitation_token
    }.freeze

    attr_accessor \
      :email,
      :invitation_token

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @email = hash[:email]
      @invitation_token = hash[:invitation_token]
    end
  end
end
