# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DeviceAuthorizationResponse
    include HashProvider

    attr_accessor \
      :device_code,
      :user_code,
      :verification_uri,
      :verification_uri_complete,
      :expires_in,
      :interval

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @device_code = hash[:device_code]
      @user_code = hash[:user_code]
      @verification_uri = hash[:verification_uri]
      @verification_uri_complete = hash[:verification_uri_complete]
      @expires_in = hash[:expires_in]
      @interval = hash[:interval]
    end

    def to_json(*)
      {
        device_code: device_code,
        user_code: user_code,
        verification_uri: verification_uri,
        verification_uri_complete: verification_uri_complete,
        expires_in: expires_in,
        interval: interval
      }
    end
  end
end
