# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class MagicAuth
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :user_id,
      :email,
      :expires_at,
      :created_at,
      :updated_at,
      :code

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @user_id = hash[:user_id]
      @email = hash[:email]
      @expires_at = hash[:expires_at]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @code = hash[:code]
    end

    def to_h
      {
        object: object,
        id: id,
        user_id: user_id,
        email: email,
        expires_at: expires_at,
        created_at: created_at,
        updated_at: updated_at,
        code: code
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

    def inspect
      "#<#{self.class} id=#{@id}>"
    end
  end
end
