# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class RadarSmsChallengeCodeSessionAuthenticateRequest < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      client_id: :client_id,
      client_secret: :client_secret,
      grant_type: :grant_type,
      code: :code,
      verification_id: :verification_id,
      phone_number: :phone_number,
      pending_authentication_token: :pending_authentication_token,
      ip_address: :ip_address,
      device_id: :device_id,
      user_agent: :user_agent
    }.freeze

    attr_accessor \
      :client_id,
      :client_secret,
      :grant_type,
      :code,
      :verification_id,
      :phone_number,
      :pending_authentication_token,
      :ip_address,
      :device_id,
      :user_agent

    def initialize(json)
      hash = self.class.normalize(json)
      @client_id = hash[:client_id]
      @client_secret = hash[:client_secret]
      @grant_type = hash[:grant_type]
      @code = hash[:code]
      @verification_id = hash[:verification_id]
      @phone_number = hash[:phone_number]
      @pending_authentication_token = hash[:pending_authentication_token]
      @ip_address = hash[:ip_address]
      @device_id = hash[:device_id]
      @user_agent = hash[:user_agent]
    end
  end
end
