# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class SendEmailChange
    include HashProvider

    HASH_ATTRS = {
      new_email: :new_email
    }.freeze

    attr_accessor :new_email

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @new_email = hash[:new_email]
    end
  end
end
