# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class SendEmailChange < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      new_email: :new_email
    }.freeze

    attr_accessor :new_email

    def initialize(json)
      hash = self.class.normalize(json)
      @new_email = hash[:new_email]
    end
  end
end
