# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module WorkOS
  class CreateConnectionSAMLOptions
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(String)) }
    def idp_metadata_url; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def idp_metadata_url=(value); end

    sig { returns(T.nilable(String)) }
    def acs_url; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def acs_url=(value); end

    sig { returns(T.nilable(String)) }
    def sp_entity_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def sp_entity_id=(value); end

    sig { returns(T.nilable(String)) }
    def idp_entity_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def idp_entity_id=(value); end

    sig { returns(T.nilable(String)) }
    def idp_sso_url; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def idp_sso_url=(value); end

    sig { returns(T.nilable(T::Array[String])) }
    def idp_signing_certs; end

    sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
    def idp_signing_certs=(value); end

    sig { returns(T.nilable(WorkOS::CreateConnectionKeyPair)) }
    def sp_signing_key_pair; end

    sig { params(value: T.nilable(WorkOS::CreateConnectionKeyPair)).returns(T.nilable(WorkOS::CreateConnectionKeyPair)) }
    def sp_signing_key_pair=(value); end

    sig { returns(T.nilable(T::Array[WorkOS::CreateConnectionKeyPair])) }
    def sp_encryption_key_pairs; end

    sig { params(value: T.nilable(T::Array[WorkOS::CreateConnectionKeyPair])).returns(T.nilable(T::Array[WorkOS::CreateConnectionKeyPair])) }
    def sp_encryption_key_pairs=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
