# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module WorkOS
  class DataIntegrationInstallation
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def id; end

    sig { params(value: String).returns(String) }
    def id=(value); end

    sig { returns(String) }
    def connection_role; end

    sig { params(value: String).returns(String) }
    def connection_role=(value); end

    sig { returns(T.nilable(String)) }
    def account_identifier; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def account_identifier=(value); end

    sig { returns(T.nilable(String)) }
    def account_display_name; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def account_display_name=(value); end

    sig { returns(T.nilable(String)) }
    def user_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def user_id=(value); end

    sig { returns(T.nilable(String)) }
    def organization_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def organization_id=(value); end

    sig { returns(T.nilable(String)) }
    def api_key_last_4; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def api_key_last_4=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
