# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module WorkOS
  class Events
    sig { params(client: WorkOS::BaseClient).void }
    def initialize(client); end

    sig do
      params(
        events: T::Array[String],
        before: T.nilable(String),
        after: T.nilable(String),
        limit: T.nilable(Integer),
        order: T.nilable(String),
        range_start: T.nilable(String),
        range_end: T.nilable(String),
        organization_id: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(WorkOS::Types::ListStruct)
    end
    def list_events(events:, before:, after:, limit:, order:, range_start:, range_end:, organization_id:, request_options:); end

  end
end
