# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module WorkOS
  class PasswordPlaintext
    sig { returns(String) }
    def password; end

    sig do
      params(
        password: String
      ).returns(WorkOS::PasswordPlaintext)
    end
    def self.new(password:); end
  end
end
