# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module WorkOS
  module PublicClient
    sig { params(client_id: String, opts: T.untyped).returns(WorkOS::Client) }
    def self.create(client_id:, **opts); end
  end
end
