# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AgentRegistrationClaim < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      claim_completion: :claim_completion,
      created_at: :created_at,
      updated_at: :updated_at,
      expires_at: :expires_at
    }.freeze

    attr_accessor \
      :id,
      :claim_completion,
      :created_at,
      :updated_at,
      :expires_at

    def initialize(json)
      hash = self.class.normalize(json)
      @id = hash[:id]
      @claim_completion = hash[:claim_completion] ? WorkOS::AgentRegistrationClaimClaimCompletion.new(hash[:claim_completion]) : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @expires_at = hash[:expires_at]
    end
  end
end
