# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AgentRegistration < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      agent_identity: :agent_identity,
      organization_id: :organization_id,
      status: :status,
      kind: :kind,
      claim: :claim,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :id,
      :agent_identity,
      :organization_id,
      :status,
      :kind,
      :claim,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @id = hash[:id]
      @agent_identity = hash[:agent_identity] ? WorkOS::AgentRegistrationAgentIdentity.new(hash[:agent_identity]) : nil
      @organization_id = hash[:organization_id]
      @status = hash[:status]
      @kind = hash[:kind]
      @claim = hash[:claim] ? WorkOS::AgentRegistrationClaim.new(hash[:claim]) : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
