# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class ClaimViewResponse < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      status: :status,
      user_code: :user_code,
      organizations: :organizations
    }.freeze

    attr_accessor \
      :id,
      :status,
      :user_code,
      :organizations

    def initialize(json)
      hash = self.class.normalize(json)
      @id = hash[:id]
      @status = hash[:status]
      @user_code = hash[:user_code]
      @organizations = (hash[:organizations] || []).map { |item| item ? WorkOS::ClaimViewResponseOrganization.new(item) : nil }
    end
  end
end
