# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class DeleteObjectResponse < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      name: :name,
      success: :success
    }.freeze

    attr_accessor \
      :name,
      :success

    def initialize(json)
      hash = self.class.normalize(json)
      @name = hash[:name]
      @success = hash[:success]
    end
  end
end
