# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AuditLogConfiguration < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      organization_id: :organization_id,
      retention_period_in_days: :retention_period_in_days,
      state: :state,
      log_stream: :log_stream
    }.freeze

    attr_accessor \
      :organization_id,
      :retention_period_in_days,
      :state,
      :log_stream

    def initialize(json)
      hash = self.class.normalize(json)
      @organization_id = hash[:organization_id]
      @retention_period_in_days = hash[:retention_period_in_days]
      @state = hash[:state]
      @log_stream = hash[:log_stream] ? WorkOS::AuditLogConfigurationLogStream.new(hash[:log_stream]) : nil
    end
  end
end
