# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class ItContact < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      email: :email,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :email,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @email = hash[:email]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
