# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class OrganizationDomainData
    include HashProvider

    HASH_ATTRS = {
      domain: :domain,
      state: :state
    }.freeze

    attr_accessor \
      :domain,
      :state

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @domain = hash[:domain]
      @state = hash[:state]
    end
  end
end
