# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class OrganizationRoleDeleted < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      event: :event,
      data: :data,
      created_at: :created_at,
      context: :context
    }.freeze

    attr_accessor \
      :object,
      :id,
      :event,
      :data,
      :created_at,
      :context

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @event = hash[:event]
      @data = hash[:data] ? WorkOS::OrganizationRoleDeletedData.new(hash[:data]) : nil
      @created_at = hash[:created_at]
      @context = hash[:context] ? WorkOS::EventContext.new(hash[:context]) : nil
    end
  end
end
