# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class OrganizationMembershipUpdatedData
    include HashProvider

    HASH_ATTRS = {
      object: :object,
      id: :id,
      user_id: :user_id,
      organization_id: :organization_id,
      status: :status,
      role: :role,
      roles: :roles,
      custom_attributes: :custom_attributes,
      directory_managed: :directory_managed,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :user_id,
      :organization_id,
      :status,
      :role,
      :roles,
      :custom_attributes,
      :directory_managed,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @user_id = hash[:user_id]
      @organization_id = hash[:organization_id]
      @status = hash[:status]
      @role = hash[:role] ? WorkOS::SlimRole.new(hash[:role]) : nil
      @roles = (hash[:roles] || []).map { |item| item ? WorkOS::SlimRole.new(item) : nil }
      @custom_attributes = hash[:custom_attributes] || {}
      @directory_managed = hash[:directory_managed]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
