# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AuditLogSchemaJson < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      object: :object,
      version: :version,
      actor: :actor,
      targets: :targets,
      metadata: :metadata,
      created_at: :created_at
    }.freeze

    attr_accessor \
      :object,
      :version,
      :actor,
      :targets,
      :metadata,
      :created_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @version = hash[:version]
      @actor = hash[:actor] ? WorkOS::AuditLogSchemaJsonActor.new(hash[:actor]) : nil
      @targets = (hash[:targets] || []).map { |item| item ? WorkOS::AuditLogSchemaJsonTarget.new(item) : nil }
      @metadata = hash[:metadata] || {}
      @created_at = hash[:created_at]
    end
  end
end
