# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class AuditLogEventActor
    include HashProvider

    HASH_ATTRS = {
      id: :id,
      type: :type,
      name: :name,
      metadata: :metadata
    }.freeze

    attr_accessor \
      :id,
      :type,
      :name,
      :metadata

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @id = hash[:id]
      @type = hash[:type]
      @name = hash[:name]
      @metadata = hash[:metadata] || {}
    end
  end
end
