# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class AuditLogSchemaActor
    include HashProvider

    HASH_ATTRS = {
      metadata: :metadata
    }.freeze

    attr_accessor :metadata

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @metadata = hash[:metadata] || {}
    end
  end
end
