# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AuditLogEventIngestion < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      organization_id: :organization_id,
      event: :event
    }.freeze

    attr_accessor \
      :organization_id,
      :event

    def initialize(json)
      hash = self.class.normalize(json)
      @organization_id = hash[:organization_id]
      @event = hash[:event] ? WorkOS::AuditLogEvent.new(hash[:event]) : nil
    end
  end
end
