# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AuditLogEventCreateResponse < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      success: :success
    }.freeze

    attr_accessor :success

    def initialize(json)
      hash = self.class.normalize(json)
      @success = hash[:success]
    end
  end
end
