# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class OrganizationDomain
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :organization_id,
      :domain,
      :state,
      :verification_prefix,
      :verification_token,
      :verification_strategy,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @organization_id = hash[:organization_id]
      @domain = hash[:domain]
      @state = hash[:state]
      @verification_prefix = hash[:verification_prefix]
      @verification_token = hash[:verification_token]
      @verification_strategy = hash[:verification_strategy]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end

    def to_h
      {
        object: object,
        id: id,
        organization_id: organization_id,
        domain: domain,
        state: state,
        verification_prefix: verification_prefix,
        verification_token: verification_token,
        verification_strategy: verification_strategy,
        created_at: created_at,
        updated_at: updated_at
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

    def inspect
      "#<#{self.class} id=#{@id}>"
    end
  end
end
