# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AgentRegistrationClaimAttemptCreatedData < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      agent_registration_id: :agent_registration_id,
      agent_registration_claim_id: :agent_registration_claim_id,
      login_hint: :login_hint,
      expires_at: :expires_at,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :agent_registration_id,
      :agent_registration_claim_id,
      :login_hint,
      :expires_at,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @agent_registration_id = hash[:agent_registration_id]
      @agent_registration_claim_id = hash[:agent_registration_claim_id]
      @login_hint = hash[:login_hint]
      @expires_at = hash[:expires_at]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
