# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AgentInstanceDeletedData < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      agent_blueprint_id: :agent_blueprint_id,
      organization_id: :organization_id,
      organization_membership_id: :organization_membership_id,
      type: :type,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :agent_blueprint_id,
      :organization_id,
      :organization_membership_id,
      :type,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @agent_blueprint_id = hash[:agent_blueprint_id]
      @organization_id = hash[:organization_id]
      @organization_membership_id = hash[:organization_membership_id]
      @type = hash[:type]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
