# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AgentRegistrationCredentialIssuedData < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      agent_registration_id: :agent_registration_id,
      detail: :detail,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    attr_accessor \
      :object,
      :id,
      :agent_registration_id,
      :detail,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @agent_registration_id = hash[:agent_registration_id]
      @detail = hash[:detail] ? (case hash[:detail][:kind] when "api_key" then WorkOS::AgentRegistrationCredentialIssuedDataDetail.new(hash[:detail]) when "access_token" then WorkOS::AccessTokenAgentRegistrationCredentialIssuedDataDetail.new(hash[:detail]) else hash[:detail] end) : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
