# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AgentRegistrationCreatedDataAgentIdentity < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      userland_user_id: :userland_user_id
    }.freeze

    attr_accessor \
      :object,
      :id,
      :userland_user_id

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @userland_user_id = hash[:userland_user_id]
    end
  end
end
