# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class AgentRegistrationCredentialIssuedDataDetail < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      kind: :kind,
      api_key_id: :api_key_id
    }.freeze

    attr_accessor \
      :kind,
      :api_key_id

    def initialize(json)
      hash = self.class.normalize(json)
      @kind = hash[:kind]
      @api_key_id = hash[:api_key_id]
    end
  end
end
