# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class ConnectionSAMLCertificateRenewalRequiredData
    include HashProvider

    attr_accessor \
      :connection,
      :certificate,
      :days_until_expiry

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @connection = hash[:connection] ? WorkOS::ConnectionSAMLCertificateRenewalRequiredDataConnection.new(hash[:connection].to_json) : nil
      @certificate = hash[:certificate] ? WorkOS::ConnectionSAMLCertificateRenewalRequiredDataCertificate.new(hash[:certificate].to_json) : nil
      @days_until_expiry = hash[:days_until_expiry]
    end

    def to_json(*)
      {
        connection: connection&.to_json,
        certificate: certificate&.to_json,
        days_until_expiry: days_until_expiry
      }
    end
  end
end
