# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class EventContext < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      google_analytics_client_id: :google_analytics_client_id,
      google_analytics_sessions: :google_analytics_sessions,
      ajs_anonymous_id: :ajs_anonymous_id,
      client_id: :client_id,
      actor: :actor,
      previous_attributes: :previous_attributes
    }.freeze

    attr_accessor \
      :google_analytics_client_id,
      :google_analytics_sessions,
      :ajs_anonymous_id,
      :client_id,
      :actor,
      :previous_attributes

    def initialize(json)
      hash = self.class.normalize(json)
      @google_analytics_client_id = hash[:google_analytics_client_id]
      @google_analytics_sessions = (hash[:google_analytics_sessions] || []).map { |item| item ? WorkOS::EventContextGoogleAnalyticsSession.new(item) : nil }
      @ajs_anonymous_id = hash[:ajs_anonymous_id]
      @client_id = hash[:client_id]
      @actor = hash[:actor] ? WorkOS::EventContextActor.new(hash[:actor]) : nil
      @previous_attributes = hash[:previous_attributes] || {}
    end
  end
end
