# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class EventContext
    include HashProvider

    HASH_ATTRS = {
      google_analytics_client_id: :google_analytics_client_id,
      google_analytics_sessions: :google_analytics_sessions,
      ajs_anonymous_id: :ajs_anonymous_id,
      client_id: :client_id,
      actor: :actor,
      previous_attributes: :previous_attributes
    }.freeze

    attr_accessor \
      :google_analytics_client_id,
      :google_analytics_sessions,
      :ajs_anonymous_id,
      :client_id,
      :actor,
      :previous_attributes

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @google_analytics_client_id = hash[:google_analytics_client_id]
      @google_analytics_sessions = (hash[:google_analytics_sessions] || []).map { |item| item ? WorkOS::EventContextGoogleAnalyticsSession.new(item) : nil }
      @ajs_anonymous_id = hash[:ajs_anonymous_id]
      @client_id = hash[:client_id]
      @actor = hash[:actor] ? WorkOS::EventContextActor.new(hash[:actor]) : nil
      @previous_attributes = hash[:previous_attributes] || {}
    end
  end
end
