# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class PermissionCreatedData
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :slug,
      :name,
      :description,
      :system,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @slug = hash[:slug]
      @name = hash[:name]
      @description = hash[:description]
      @system = hash[:system]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end

    def to_json(*)
      {
        object: object,
        id: id,
        slug: slug,
        name: name,
        description: description,
        system: system,
        created_at: created_at,
        updated_at: updated_at
      }
    end
  end
end
