# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class PipesConnectedAccountConnectionFailedData < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      data_integration_id: :data_integration_id,
      provider_slug: :provider_slug,
      user_id: :user_id,
      organization_id: :organization_id,
      error_code: :error_code,
      error_reason: :error_reason,
      provider_error: :provider_error,
      provider_error_description: :provider_error_description,
      created_at: :created_at
    }.freeze

    attr_accessor \
      :object,
      :data_integration_id,
      :provider_slug,
      :user_id,
      :organization_id,
      :error_code,
      :error_reason,
      :provider_error,
      :provider_error_description,
      :created_at

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @data_integration_id = hash[:data_integration_id]
      @provider_slug = hash[:provider_slug]
      @user_id = hash[:user_id]
      @organization_id = hash[:organization_id]
      @error_code = hash[:error_code]
      @error_reason = hash[:error_reason]
      @provider_error = hash[:provider_error]
      @provider_error_description = hash[:provider_error_description]
      @created_at = hash[:created_at]
    end
  end
end
