# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class WaitlistUserCreated < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      id: :id,
      event: :event,
      data: :data,
      created_at: :created_at,
      context: :context,
      object: :object
    }.freeze

    attr_accessor \
      :id,
      :event,
      :data,
      :created_at,
      :context,
      :object

    def initialize(json)
      hash = self.class.normalize(json)
      @id = hash[:id]
      @event = hash[:event]
      @data = hash[:data] ? WorkOS::WaitlistUser.new(hash[:data]) : nil
      @created_at = hash[:created_at]
      @context = hash[:context] ? WorkOS::EventContext.new(hash[:context]) : nil
      @object = hash[:object]
    end
  end
end
