# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class GenerateLink < WorkOS::Types::BaseModel

    HASH_ATTRS = {
      return_url: :return_url,
      success_url: :success_url,
      organization: :organization,
      intent: :intent,
      intent_options: :intent_options,
      it_contact_emails: :it_contact_emails
    }.freeze

    attr_accessor \
      :return_url,
      :success_url,
      :organization,
      :intent,
      :intent_options,
      :it_contact_emails

    def initialize(json)
      hash = self.class.normalize(json)
      @return_url = hash[:return_url]
      @success_url = hash[:success_url]
      @organization = hash[:organization]
      @intent = hash[:intent]
      @intent_options = hash[:intent_options] ? WorkOS::IntentOptions.new(hash[:intent_options]) : nil
      @it_contact_emails = (hash[:it_contact_emails] || [])
    end
  end
end
