# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DataIntegrationAuthorizeUrlResponse
    include HashProvider

    attr_accessor :url

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @url = hash[:url]
    end

    def to_h
      {
        url: url
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end
  end
end
