# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class DataIntegrationsListResponseData
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :name,
      :description,
      :slug,
      :integration_type,
      :credentials_type,
      :scopes,
      :ownership,
      :created_at,
      :updated_at,
      :connected_account

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @name = hash[:name]
      @description = hash[:description]
      @slug = hash[:slug]
      @integration_type = hash[:integration_type]
      @credentials_type = hash[:credentials_type]
      @scopes = hash[:scopes] || []
      @ownership = hash[:ownership]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @connected_account = hash[:connected_account] ? WorkOS::DataIntegrationsListResponseDataConnectedAccount.new(hash[:connected_account]) : nil
    end

    def to_h
      {
        object: object,
        id: id,
        name: name,
        description: description,
        slug: slug,
        integration_type: integration_type,
        credentials_type: credentials_type,
        scopes: scopes,
        ownership: ownership,
        created_at: created_at,
        updated_at: updated_at,
        connected_account: connected_account&.to_h
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end
  end
end
