# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class DataIntegrationInstallation < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      user_id: :user_id,
      organization_id: :organization_id,
      api_key_last_4: :api_key_last_4
    }.freeze

    attr_accessor \
      :id,
      :user_id,
      :organization_id,
      :api_key_last_4

    def initialize(json)
      hash = self.class.normalize(json)
      @id = hash[:id]
      @user_id = hash[:user_id]
      @organization_id = hash[:organization_id]
      @api_key_last_4 = hash[:api_key_last_4]
    end
  end
end
