# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class DataIntegrationsListResponseDataConnectedAccount < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      user_id: :user_id,
      organization_id: :organization_id,
      scopes: :scopes,
      state: :state,
      created_at: :created_at,
      updated_at: :updated_at,
      userlandUserId: :userland_user_id
    }.freeze

    # @!attribute userland_user_id
    #   @deprecated Use `user_id` instead.

    attr_accessor \
      :object,
      :id,
      :user_id,
      :organization_id,
      :scopes,
      :state,
      :created_at,
      :updated_at

    def userland_user_id
      warn "[DEPRECATION] `userland_user_id` is deprecated and will be removed in a future version.", uplevel: 1
      @userland_user_id
    end

    attr_writer :userland_user_id

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @user_id = hash[:user_id]
      @organization_id = hash[:organization_id]
      @scopes = hash[:scopes] || []
      @state = hash[:state]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @userland_user_id = hash[:userlandUserId]
    end
  end
end
