# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class DataIntegrationCredentialsResponse < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      active: :active,
      credential: :credential,
      error: :error
    }.freeze

    attr_accessor \
      :active,
      :credential,
      :error

    def initialize(json)
      hash = self.class.normalize(json)
      @active = hash[:active]
      @credential = hash[:credential] ? WorkOS::DataIntegrationCredentialsResponseCredential.new(hash[:credential]) : nil
      @error = hash[:error]
    end
  end
end
