# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class UpdateDataIntegration < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      description: :description,
      enabled: :enabled,
      scopes: :scopes,
      credentials: :credentials,
      api_key: :api_key,
      custom_provider: :custom_provider
    }.freeze

    attr_accessor \
      :description,
      :enabled,
      :scopes,
      :credentials,
      :api_key,
      :custom_provider

    def initialize(json)
      hash = self.class.normalize(json)
      @description = hash[:description]
      @enabled = hash[:enabled]
      @scopes = hash[:scopes] || []
      @credentials = hash[:credentials] ? WorkOS::DataIntegrationCredentialsInput.new(hash[:credentials]) : nil
      @api_key = hash[:api_key] ? WorkOS::ApiKeyInstallation.new(hash[:api_key]) : nil
      @custom_provider = hash[:custom_provider] ? WorkOS::UpdateCustomProviderDefinition.new(hash[:custom_provider]) : nil
    end
  end
end
