# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class RadarStandaloneDeleteRadarListEntryRequest < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      entry: :entry
    }.freeze

    attr_accessor :entry

    def initialize(json)
      hash = self.class.normalize(json)
      @entry = hash[:entry]
    end
  end
end
