# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class RadarStandaloneResponse
    include HashProvider

    HASH_ATTRS = {
      verdict: :verdict,
      reason: :reason,
      attempt_id: :attempt_id,
      control: :control,
      blocklist_type: :blocklist_type
    }.freeze

    attr_accessor \
      :verdict,
      :reason,
      :attempt_id,
      :control,
      :blocklist_type

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @verdict = hash[:verdict]
      @reason = hash[:reason]
      @attempt_id = hash[:attempt_id]
      @control = hash[:control]
      @blocklist_type = hash[:blocklist_type]
    end
  end
end
