# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class RadarStandaloneUpdateRadarAttemptRequest < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      challenge_status: :challenge_status,
      attempt_status: :attempt_status
    }.freeze

    attr_accessor \
      :challenge_status,
      :attempt_status

    def initialize(json)
      hash = self.class.normalize(json)
      @challenge_status = hash[:challenge_status]
      @attempt_status = hash[:attempt_status]
    end
  end
end
