# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class RadarStandaloneUpdateRadarAttemptRequest
    include HashProvider

    HASH_ATTRS = {
      challenge_status: :challenge_status,
      attempt_status: :attempt_status
    }.freeze

    attr_accessor \
      :challenge_status,
      :attempt_status

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @challenge_status = hash[:challenge_status]
      @attempt_status = hash[:attempt_status]
    end
  end
end
