name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: |
          bundle exec rake test
