name: Release

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure RubyGems credentials
        uses: rubygems/configure-rubygems-credentials@a251ea8ec8e94203b26acddd2010f89b187a44b7
        with:
          role-to-assume: rg_oidc_akr_fn8dx45asckvmsnd2kka

      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # 6.1.0

      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # 1.321.0
        with:
          bundler-cache: true

      - name: Publish to RubyGems
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          bundle exec rake build
          gem push pkg/workos-${VERSION}.gem --host https://rubygems.org
