# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class ApiKeyValidationResponse
    include HashProvider

    attr_accessor :api_key

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @api_key = hash[:api_key] ? WorkOS::ApiKey.new(hash[:api_key]) : nil
    end

    def to_h
      {
        api_key: api_key&.to_h
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

    def inspect
      "#<#{self.class}>"
    end
  end
end
