# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class ApiKeyUpdatedData < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      object: :object,
      id: :id,
      owner: :owner,
      name: :name,
      obfuscated_value: :obfuscated_value,
      last_used_at: :last_used_at,
      expires_at: :expires_at,
      permissions: :permissions,
      created_at: :created_at,
      updated_at: :updated_at,
      previous_attributes: :previous_attributes
    }.freeze

    attr_accessor \
      :object,
      :id,
      :owner,
      :name,
      :obfuscated_value,
      :last_used_at,
      :expires_at,
      :permissions,
      :created_at,
      :updated_at,
      :previous_attributes

    def initialize(json)
      hash = self.class.normalize(json)
      @object = hash[:object]
      @id = hash[:id]
      @owner = hash[:owner] ? (case hash[:owner][:type] when "organization" then WorkOS::ApiKeyUpdatedDataOwner.new(hash[:owner]) when "user" then WorkOS::UserApiKeyUpdatedDataOwner.new(hash[:owner]) else hash[:owner] end) : nil
      @name = hash[:name]
      @obfuscated_value = hash[:obfuscated_value]
      @last_used_at = hash[:last_used_at]
      @expires_at = hash[:expires_at]
      @permissions = hash[:permissions] || []
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @previous_attributes = hash[:previous_attributes] ? WorkOS::ApiKeyUpdatedDataPreviousAttribute.new(hash[:previous_attributes]) : nil
    end
  end
end
