# This file is auto-generated by oagen. Do not edit.

require "json"

module WorkOS
  class AuthenticationFactor
    include HashProvider

    attr_accessor \
      :object,
      :id,
      :type,
      :user_id,
      :sms,
      :totp,
      :created_at,
      :updated_at

    def initialize(json)
      hash = json.is_a?(Hash) ? json : JSON.parse(json, symbolize_names: true)
      hash = hash.transform_keys(&:to_sym) if hash.keys.first.is_a?(String)
      @object = hash[:object]
      @id = hash[:id]
      @type = hash[:type]
      @user_id = hash[:user_id]
      @sms = hash[:sms] ? WorkOS::AuthenticationFactorSms.new(hash[:sms].to_json) : nil
      @totp = hash[:totp] ? WorkOS::AuthenticationFactorTotp.new(hash[:totp].to_json) : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end

    def to_json(*)
      {
        object: object,
        id: id,
        type: type,
        user_id: user_id,
        sms: sms&.to_json,
        totp: totp&.to_json,
        created_at: created_at,
        updated_at: updated_at
      }
    end
  end
end
