# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module WorkOS
  class EnrollUserAuthenticationFactor < WorkOS::Types::BaseModel
    HASH_ATTRS = {
      type: :type,
      totp_issuer: :totp_issuer,
      totp_user: :totp_user,
      totp_secret: :totp_secret
    }.freeze

    attr_accessor \
      :type,
      :totp_issuer,
      :totp_user,
      :totp_secret

    def initialize(json)
      hash = self.class.normalize(json)
      @type = hash[:type]
      @totp_issuer = hash[:totp_issuer]
      @totp_user = hash[:totp_user]
      @totp_secret = hash[:totp_secret]
    end
  end
end
